<?php
/** Manual smoke check for Editorial Humanizer without external APIs or DB. */
if ( ! defined( 'ABSPATH' ) ) { define( 'ABSPATH', dirname( __DIR__, 2 ) . '/' ); }
$GLOBALS['obe_external_calls'] = 0; $GLOBALS['obe_posts']=array(); $GLOBALS['obe_meta']=array(); $GLOBALS['obe_created']=array();
if ( ! function_exists( '__' ) ) { function __( $text ) { return $text; } }
if ( ! function_exists( 'esc_html__' ) ) { function esc_html__( $text ) { return $text; } }
if ( ! function_exists( 'sanitize_key' ) ) { function sanitize_key( $key ) { return preg_replace( '/[^a-z0-9_\-]/', '', strtolower( (string) $key ) ); } }
if ( ! function_exists( 'sanitize_text_field' ) ) { function sanitize_text_field( $v ) { return trim( strip_tags( (string) $v ) ); } }
if ( ! function_exists( 'sanitize_textarea_field' ) ) { function sanitize_textarea_field( $v ) { return trim( strip_tags( (string) $v ) ); } }
if ( ! function_exists( 'wp_kses_post' ) ) { function wp_kses_post( $v ) { return (string) $v; } }
if ( ! function_exists( 'wp_strip_all_tags' ) ) { function wp_strip_all_tags( $v ) { return strip_tags( (string) $v ); } }
if ( ! function_exists( 'wp_json_encode' ) ) { function wp_json_encode( $v ) { return json_encode( $v ); } }
if ( ! function_exists( 'wpautop' ) ) { function wpautop( $v ) { return '<p>' . $v . '</p>'; } }
if ( ! function_exists( 'esc_html' ) ) { function esc_html( $v ) { return htmlspecialchars( (string) $v, ENT_QUOTES, 'UTF-8' ); } }
if ( ! function_exists( 'absint' ) ) { function absint( $v ) { return max( 0, (int) $v ); } }
if ( ! function_exists( 'is_wp_error' ) ) { function is_wp_error( $v ) { return false; } }
if ( ! function_exists( 'get_current_user_id' ) ) { function get_current_user_id() { return 1; } }
if ( ! function_exists( 'wp_insert_post' ) ) { function wp_insert_post( $data, $wp_error = false ) { $id=222; $GLOBALS['obe_posts'][$id]=new WP_Post(array('ID'=>$id,'post_type'=>$data['post_type'],'post_title'=>$data['post_title'],'post_content'=>$data['post_content'],'post_author'=>$data['post_author'],'post_date'=>gmdate('c'),'post_modified'=>gmdate('c'))); $GLOBALS['obe_created']=$data; return $id; } }
if ( ! function_exists( 'update_post_meta' ) ) { function update_post_meta( $id, $key, $value ) { $GLOBALS['obe_meta'][$id][$key]=$value; return true; } }
if ( ! function_exists( 'get_post_meta' ) ) { function get_post_meta( $id, $key, $single = true ) { return $GLOBALS['obe_meta'][$id][$key] ?? ''; } }
if ( ! function_exists( 'get_post' ) ) { function get_post( $id ) { return $GLOBALS['obe_posts'][$id] ?? null; } }
if ( ! function_exists( 'get_the_title' ) ) { function get_the_title( $post ) { return $post->post_title; } }
if ( ! function_exists( 'wp_generate_uuid4' ) ) { function wp_generate_uuid4() { return '00000000-0000-4000-8000-000000000000'; } }
if ( ! function_exists( 'get_option' ) ) { function get_option( $k, $d = false ) { return $d; } }
if ( ! function_exists( 'sanitize_email' ) ) { function sanitize_email( $v ) { return (string)$v; } }
if ( ! class_exists( 'WP_Error' ) ) { class WP_Error {} }
if ( ! class_exists( 'WP_Post' ) ) { class WP_Post { public $ID; public $post_type; public $post_title; public $post_content; public $post_author; public $post_date; public $post_modified; public function __construct( array $d ) { foreach ( $d as $k => $v ) { $this->$k = $v; } } } }
require_once ABSPATH.'includes/Support/Capabilities.php'; require_once ABSPATH.'includes/Support/Secret_Masker.php'; require_once ABSPATH.'includes/AI/Model_Profile.php'; require_once ABSPATH.'includes/AI/AI_Task_Type.php'; require_once ABSPATH.'includes/AI/Structured_Output.php'; require_once ABSPATH.'includes/AI/AI_Task_Profile_Resolver.php'; require_once ABSPATH.'includes/AI/AI_Request.php'; require_once ABSPATH.'includes/AI/AI_Error.php'; require_once ABSPATH.'includes/AI/Usage_Record.php'; require_once ABSPATH.'includes/AI/AI_Response.php'; require_once ABSPATH.'includes/AI/AI_Response_Normalizer.php'; require_once ABSPATH.'includes/Providers/Provider_Interface.php'; require_once ABSPATH.'includes/Providers/Provider_Settings.php'; require_once ABSPATH.'includes/Providers/Provider_Resolver.php'; require_once ABSPATH.'includes/Providers/OpenAI/OpenAI_Provider.php'; require_once ABSPATH.'includes/AI/AI_Request_Builder.php'; require_once ABSPATH.'includes/AI/AI_Engine.php'; require_once ABSPATH.'includes/Activity/Activity_Action.php'; require_once ABSPATH.'includes/Activity/Activity_Status.php'; require_once ABSPATH.'includes/Activity/Activity_Object_Type.php'; require_once ABSPATH.'includes/Activity/Activity_Repository.php'; require_once ABSPATH.'includes/Activity/Activity_Logger.php'; require_once ABSPATH.'includes/Library/Library_Type.php'; require_once ABSPATH.'includes/Library/Library_Status.php'; require_once ABSPATH.'includes/Library/Library_Item.php'; require_once ABSPATH.'includes/Library/Library_Repository.php'; require_once ABSPATH.'includes/Editorial/Editorial_Tone.php'; require_once ABSPATH.'includes/Editorial/Editorial_Revision.php'; require_once ABSPATH.'includes/Editorial/Editorial_Humanizer_Service.php';
use OBEngine\AI\AI_Engine; use OBEngine\AI\AI_Request; use OBEngine\AI\AI_Response; use OBEngine\AI\AI_Request_Builder; use OBEngine\AI\AI_Response_Normalizer; use OBEngine\Providers\Provider_Interface; use OBEngine\Providers\Provider_Resolver; use OBEngine\Editorial\Editorial_Tone; use OBEngine\Editorial\Editorial_Revision; use OBEngine\Editorial\Editorial_Humanizer_Service; use OBEngine\Library\Library_Repository; use OBEngine\Library\Library_Type; use OBEngine\Library\Library_Status;
class EditorialFakeProvider implements Provider_Interface { public function provider_id(): string { return 'fake'; } public function supports( string $c ): bool { return in_array($c,array(self::CAPABILITY_TEXT_GENERATION,self::CAPABILITY_STRUCTURED_OUTPUT),true); } public function generate( AI_Request $r ): AI_Response { $GLOBALS['obe_external_calls']++; return AI_Response::completed($r,array('provider'=>'fake','model'=>'fake-model','output_json'=>array('revised_title'=>'Revised Safe Title','revised_content'=>'Clear revised content for readers.','revised_excerpt'=>'Clear excerpt.','readability_score'=>91,'tone_score'=>88,'localization_score'=>86,'revision_notes'=>array('Improved clarity.'),'safety_notes'=>array('Human review required.'),'default_status'=>'needs_review'))); } }
function ehs_assert($c,$m){ if(!$c){ fwrite(STDERR,"FAIL: $m\n"); exit(1);} }
$GLOBALS['obe_posts'][111]=new WP_Post(array('ID'=>111,'post_type'=>Library_Repository::POST_TYPE,'post_title'=>'Original Draft','post_content'=>'Original source content should remain unchanged.','post_author'=>1,'post_date'=>gmdate('c'),'post_modified'=>gmdate('c')));
$GLOBALS['obe_meta'][111]=array(Library_Repository::META_TYPE=>Library_Type::CONTENT_DRAFT,Library_Repository::META_STATUS=>Library_Status::NEEDS_REVIEW,Library_Repository::META_SUMMARY=>'Original summary.',Library_Repository::META_SOURCE_LABEL=>'Manual',Library_Repository::META_PAYLOAD_REDACTED=>'',Library_Repository::META_CREATED_CONTEXT=>'manual');
ehs_assert(Editorial_Tone::is_valid(Editorial_Tone::NATURAL),'valid tone works'); foreach(Editorial_Tone::all() as $tone){ ehs_assert(false===strpos($tone,'detect'),'no detector tone'); }
$empty=Editorial_Revision::empty(); ehs_assert(in_array($empty->get_default_status(),array('needs_review','draft'),true),'empty default status safe');
$partial=Editorial_Revision::from_ai_response_data(array('tone'=>'bad','readability_score'=>999),array('source_library_item_id'=>111)); ehs_assert(Editorial_Tone::NATURAL===$partial->get_tone(),'invalid tone normalizes'); ehs_assert(100===$partial->to_array()['readability_score'],'score clamps');
$engine=new AI_Engine(null,new Provider_Resolver(array('fake'=>new EditorialFakeProvider()),'fake'),new AI_Response_Normalizer()); $service=new Editorial_Humanizer_Service($engine,new Library_Repository());
ehs_assert(false===$service->validate_data(array())['success'],'source id required'); $item=(new Library_Repository())->get(111); $task=$service->build_ai_task_data(array('tone'=>'editorial','editorial_notes'=>''),$item); ehs_assert('editorial_revision'===$task['task_type'],'task type editorial_revision'); ehs_assert('editorial_revision_v1'===$task['output_schema'],'schema editorial_revision_v1'); $task_input=json_decode($task['input'],true); ehs_assert('editorial'===$task_input['selected_tone'],'selected tone included in input'); ehs_assert('Editorial'===$task_input['selected_tone_label'],'selected tone label included in input'); ehs_assert(false!==strpos($task['instructions'],'Apply the selected editorial tone: Editorial.'),'tone instruction included'); ehs_assert('editorial'===$task['metadata']['tone'],'metadata tone preserved'); ehs_assert('editorial'===$task['metadata']['selected_tone'],'selected tone included in metadata');
$lib=$service->build_library_data(Editorial_Revision::from_ai_response_data(array('revised_title'=>'T','revised_content'=>'C'),array('source_library_item_id'=>111,'source_title'=>'S')),$task); ehs_assert(Library_Type::EDITORIAL_REVISION===$lib['type'],'library type editorial_revision'); ehs_assert(Library_Status::NEEDS_REVIEW===$lib['status'],'status needs_review'); ehs_assert(false===strpos($lib['payload_redacted'],'raw prompt'),'payload no raw prompt'); ehs_assert(false===strpos($lib['payload_redacted'],'Original source content'),'payload no raw source input');
$result=$service->create_revision(array('source_library_item_id'=>111,'tone'=>'bahasa_indonesia','editorial_notes'=>'Improve clarity.')); ehs_assert($result['success'],'service succeeds'); ehs_assert(222===$result['library_item_id'],'fake library id returned'); ehs_assert('Original source content should remain unchanged.'===$GLOBALS['obe_posts'][111]->post_content,'original not mutated'); ehs_assert(1===$GLOBALS['obe_external_calls'],'only explicit fake provider call made');
echo "Editorial Humanizer smoke passed without external APIs or DB.\n";
