<?php
/** Auto Post / Import source intake preview admin page. @package OBEngine\Admin */
namespace OBEngine\Admin;
use OBEngine\Library\Library_Type;
use OBEngine\AutoPost\Auto_Post_Plan;
use OBEngine\AutoPost\Auto_Post_Plan_Service;
use OBEngine\AutoPost\Auto_Post_Draft;
use OBEngine\AutoPost\Auto_Post_Draft_Service;
use OBEngine\Library\Library_Repository;
use OBEngine\Sources\Field_Mapping_Plan;
use OBEngine\Sources\Field_Mapping_Service;
use OBEngine\Sources\Field_Target;
use OBEngine\Sources\Source_Intake_Service;
use OBEngine\Sources\Source_Preview;
use OBEngine\Sources\Source_Type;
use OBEngine\Support\Capabilities;
use OBEngine\Support\View;
defined( 'ABSPATH' ) || exit;
final class Auto_Post_Import_Page {
	private const NONCE_ACTION = 'obe_source_intake_preview'; private const NONCE_NAME = 'obe_source_intake_preview_nonce'; private const MAPPING_NONCE_ACTION = 'obe_field_mapping_validation'; private const MAPPING_NONCE_NAME = 'obe_field_mapping_validation_nonce'; private const PLAN_NONCE_ACTION = 'obe_auto_post_plan_generation'; private const PLAN_NONCE_NAME = 'obe_auto_post_plan_generation_nonce'; private const DRAFT_NONCE_ACTION = 'obe_auto_post_draft_generation'; private const DRAFT_NONCE_NAME = 'obe_auto_post_draft_generation_nonce';
	public function render(): void { if ( ! current_user_can( Capabilities::MANAGE ) ) { wp_die( esc_html__( 'You do not have permission to manage OBE Auto Post / Import.', 'ob-engine' ) ); } $result=null; $mapping_result=null; $mapping_plan=null; $plan_result=null; $draft_result=null; $selected_preview_id=isset($_GET['source_preview_id'])?absint($_GET['source_preview_id']):0; $data=$this->default_form_data(); if ( 'POST' === $_SERVER['REQUEST_METHOD'] && isset( $_POST['obe_source_preview_action'] ) ) { check_admin_referer( self::NONCE_ACTION, self::NONCE_NAME ); $data=$this->posted_data(); $result=(new Source_Intake_Service())->create_preview($data); $data['source_input']=''; } if ( 'POST' === $_SERVER['REQUEST_METHOD'] && isset($_POST['obe_field_mapping_action']) ) { check_admin_referer( self::MAPPING_NONCE_ACTION, self::MAPPING_NONCE_NAME ); $mapping_service=new Field_Mapping_Service(); $action=sanitize_key((string)$_POST['obe_field_mapping_action']); $mapping_data=$this->posted_mapping_data(); $selected_preview_id=$mapping_data['source_preview_library_item_id']; if('suggest'===$action){ $mapping_plan=$mapping_service->build_suggested_plan_from_source_preview($selected_preview_id); } elseif('save'===$action){ $mapping_result=$mapping_service->save_mapping_plan($mapping_data); if(isset($mapping_result['plan']) && $mapping_result['plan'] instanceof Field_Mapping_Plan){$mapping_plan=$mapping_result['plan'];} } } if ( 'POST' === $_SERVER['REQUEST_METHOD'] && isset($_POST['obe_auto_post_plan_action']) ) { check_admin_referer( self::PLAN_NONCE_ACTION, self::PLAN_NONCE_NAME ); $plan_result=(new Auto_Post_Plan_Service())->generate_plan($this->posted_plan_data()); } if ( 'POST' === $_SERVER['REQUEST_METHOD'] && isset($_POST['obe_auto_post_draft_action']) ) { check_admin_referer( self::DRAFT_NONCE_ACTION, self::DRAFT_NONCE_NAME ); $draft_result=(new Auto_Post_Draft_Service())->generate_draft($this->posted_draft_data()); } ?>
		<div class="wrap ob-engine-wrap ob-engine-page-form">
			<?php View::heading( __( 'Auto Post / Import', 'ob-engine' ) ); ?>
			<?php $this->render_notices( $result ); $this->render_mapping_notice( $mapping_result ); $this->render_plan_notice( $plan_result ); $this->render_draft_notice( $draft_result ); ?>
			<div class="notice notice-info inline"><p><?php esc_html_e( 'Bundled Community Addon: Auto Post / Import. Preview source data before mapping, generation, approval, or WordPress writes.', 'ob-engine' ); ?></p></div>
			<div class="notice notice-warning inline"><p><?php esc_html_e( 'Source Intake Preview and Mapping + Validation do not call AI. Auto Post Plan and Auto Post Draft Candidate call AI only after explicit admin action. No section writes or publishes WordPress posts; actual WordPress write remains only through Library detail approval, dry-run, and Write draft flow.', 'ob-engine' ); ?></p></div>
			<form method="post" action="" class="ob-engine-card">
				<?php wp_nonce_field( self::NONCE_ACTION, self::NONCE_NAME ); ?><input type="hidden" name="obe_source_preview_action" value="preview" />
				<h2><?php esc_html_e( 'Source Intake Preview', 'ob-engine' ); ?></h2><table class="form-table" role="presentation"><tbody>
				<tr><th scope="row"><label for="obe-source-label"><?php esc_html_e( 'Source label', 'ob-engine' ); ?></label></th><td><input class="regular-text" id="obe-source-label" name="obe_source_preview[source_label]" type="text" value="<?php echo esc_attr( $data['source_label'] ); ?>" placeholder="<?php echo esc_attr__( 'Manual Source', 'ob-engine' ); ?>" /></td></tr>
				<tr><th scope="row"><label for="obe-source-type"><?php esc_html_e( 'Source type', 'ob-engine' ); ?></label></th><td><select id="obe-source-type" name="obe_source_preview[source_type]"><option value="auto"><?php esc_html_e( 'Auto-detect', 'ob-engine' ); ?></option><?php foreach ( Source_Type::labels() as $type => $label ) : ?><option value="<?php echo esc_attr( $type ); ?>" <?php selected( $data['source_type'], $type ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></td></tr>
				<tr><th scope="row"><label for="obe-source-input"><?php esc_html_e( 'Source input', 'ob-engine' ); ?> <span class="description"><?php esc_html_e( 'Required', 'ob-engine' ); ?></span></label></th><td><textarea id="obe-source-input" name="obe_source_preview[source_input]" rows="12" class="large-text" maxlength="20000" required><?php echo esc_textarea( $data['source_input'] ); ?></textarea><p class="description"><?php esc_html_e( 'Paste up to 20,000 characters. OBE stores only a redacted preview summary, not the full raw input.', 'ob-engine' ); ?></p></td></tr>
				</tbody></table><p class="submit"><button type="submit" class="button button-primary"><?php esc_html_e( 'Preview and save to Library', 'ob-engine' ); ?></button> <a class="button button-secondary" href="<?php echo esc_url( admin_url( 'admin.php?page=' . Admin_Menu::LIBRARY_SLUG ) ); ?>"><?php esc_html_e( 'View Library', 'ob-engine' ); ?></a></p>
			</form>
			<?php if ( is_array( $result ) && ! empty( $result['preview'] ) && $result['preview'] instanceof Source_Preview ) : $this->render_preview_card( $result['preview'] ); endif; ?>
			<?php $this->render_mapping_section( $selected_preview_id, $mapping_plan, $mapping_result ); ?>
			<?php $this->render_plan_section( $plan_result ); ?>
			<?php $this->render_draft_section( $draft_result ); ?>
		</div><?php }


	private function render_draft_section( $draft_result ): void { $items=(new Library_Repository())->query(array('type'=>Library_Type::AUTO_POST_PLAN,'limit'=>20)); echo '<div class="ob-engine-card"><h2>'.esc_html__('Auto Post Draft Candidate','ob-engine').'</h2><p>'.esc_html__('Generate a review-first draft candidate from an Auto Post Plan only after explicit admin action. The draft is saved to Library and does not write or publish WordPress posts.','ob-engine').'</p><form method="post" action="">'; wp_nonce_field(self::DRAFT_NONCE_ACTION,self::DRAFT_NONCE_NAME); echo '<input type="hidden" name="obe_auto_post_draft_action" value="generate" /><table class="form-table" role="presentation"><tbody><tr><th scope="row"><label for="obe-auto-post-plan-library-item-id">'.esc_html__('Auto Post Plan','ob-engine').'</label></th><td><select id="obe-auto-post-plan-library-item-id" name="obe_auto_post_draft[auto_post_plan_library_item_id]">'; foreach($items as $item){ $label=$item->get_title(); if(''!==$item->get_source_label()){$label.=' — '.$item->get_source_label();} if(''!==$item->get_updated_at()){$label.=' — '.$item->get_updated_at();} echo '<option value="'.esc_attr((string)$item->get_id()).'">'.esc_html($label).'</option>'; } echo '</select></td></tr><tr><th scope="row"><label for="obe-auto-post-draft-notes">'.esc_html__('Additional drafting notes','ob-engine').'</label></th><td><textarea id="obe-auto-post-draft-notes" name="obe_auto_post_draft[additional_instructions]" rows="5" class="large-text"></textarea><p class="description">'.esc_html__('Optional public-safe drafting notes. Do not paste raw private source data.','ob-engine').'</p></td></tr></tbody></table><p class="submit"><button type="submit" class="button button-primary">'.esc_html__('Generate draft and save to Library','ob-engine').'</button></p></form>'; if(is_array($draft_result) && !empty($draft_result['draft']) && $draft_result['draft'] instanceof Auto_Post_Draft){ $this->render_draft_card($draft_result['draft']); } echo '</div>'; }
	private function render_draft_card( Auto_Post_Draft $draft ): void { echo '<div class="ob-engine-plan-card"><h3>'.esc_html__('Draft summary','ob-engine').'</h3><table class="widefat striped"><tbody>'; echo '<tr><th>'.esc_html__('Title','ob-engine').'</th><td>'.esc_html($draft->get_title()).'</td></tr>'; echo '<tr><th>'.esc_html__('Excerpt','ob-engine').'</th><td>'.esc_html($draft->get_excerpt()).'</td></tr>'; echo '<tr><th>'.esc_html__('Meta title','ob-engine').'</th><td>'.esc_html($draft->get_meta_title()).'</td></tr>'; echo '<tr><th>'.esc_html__('Meta description','ob-engine').'</th><td>'.esc_html($draft->get_meta_description()).'</td></tr>'; echo '<tr><th>'.esc_html__('Safety notes','ob-engine').'</th><td>'.esc_html(implode('; ',$draft->get_safety_notes())).'</td></tr>'; echo '</tbody></table></div>'; }
	private function render_draft_notice( $result ): void { if(!is_array($result)){return;} if(!empty($result['success'])){ $url=admin_url('admin.php?page='.Admin_Menu::LIBRARY_SLUG.'&library_view=detail&item_id='.absint($result['library_item_id'])); echo '<div class="notice notice-success is-dismissible"><p>'.esc_html($result['message_public']).' <a href="'.esc_url($url).'">'.esc_html__('Back to Library','ob-engine').'</a></p></div>'; } else { echo '<div class="notice notice-error is-dismissible"><p>'.esc_html($result['message_public'] ?? __('Auto Post draft generation failed.','ob-engine')).'</p></div>'; } }

	private function render_plan_section( $plan_result ): void { $items=(new Library_Repository())->query(array('type'=>Library_Type::FIELD_MAPPING,'limit'=>20)); echo '<div class="ob-engine-card"><h2>'.esc_html__('Auto Post Plan','ob-engine').'</h2><p>'.esc_html__('Generate a review-first plan from a validated field mapping only after explicit admin action. The plan is saved to Library and does not write or publish WordPress posts.','ob-engine').'</p><form method="post" action="">'; wp_nonce_field(self::PLAN_NONCE_ACTION,self::PLAN_NONCE_NAME); echo '<input type="hidden" name="obe_auto_post_plan_action" value="generate" /><table class="form-table" role="presentation"><tbody><tr><th scope="row"><label for="obe-field-mapping-library-item-id">'.esc_html__('Field Mapping','ob-engine').'</label></th><td><select id="obe-field-mapping-library-item-id" name="obe_auto_post_plan[field_mapping_library_item_id]">'; foreach($items as $item){ $label=$item->get_title(); if(''!==$item->get_source_label()){$label.=' — '.$item->get_source_label();} if(''!==$item->get_updated_at()){$label.=' — '.$item->get_updated_at();} echo '<option value="'.esc_attr((string)$item->get_id()).'">'.esc_html($label).'</option>'; } echo '</select></td></tr><tr><th scope="row"><label for="obe-auto-post-plan-notes">'.esc_html__('Additional planning notes','ob-engine').'</label></th><td><textarea id="obe-auto-post-plan-notes" name="obe_auto_post_plan[additional_instructions]" rows="5" class="large-text"></textarea><p class="description">'.esc_html__('Optional public-safe planning notes. Do not paste raw private source data.','ob-engine').'</p></td></tr></tbody></table><p class="submit"><button type="submit" class="button button-primary">'.esc_html__('Generate plan and save to Library','ob-engine').'</button></p></form>'; if(is_array($plan_result) && !empty($plan_result['plan']) && $plan_result['plan'] instanceof Auto_Post_Plan){ $this->render_plan_card($plan_result['plan']); } echo '</div>'; }
	private function render_plan_card( Auto_Post_Plan $plan ): void { echo '<div class="ob-engine-plan-card"><h3>'.esc_html__('Plan summary','ob-engine').'</h3><table class="widefat striped"><tbody>'; echo '<tr><th>'.esc_html__('Proposed post type','ob-engine').'</th><td>'.esc_html($plan->get_proposed_post_type()).'</td></tr>'; echo '<tr><th>'.esc_html__('Default status','ob-engine').'</th><td>'.esc_html($plan->get_default_status()).'</td></tr>'; echo '<tr><th>'.esc_html__('Title options','ob-engine').'</th><td>'.esc_html(implode('; ',$plan->get_title_options())).'</td></tr>'; echo '<tr><th>'.esc_html__('Outline summary','ob-engine').'</th><td>'.esc_html(wp_json_encode($plan->get_outline())).'</td></tr>'; echo '<tr><th>'.esc_html__('Safety notes','ob-engine').'</th><td>'.esc_html(implode('; ',$plan->get_safety_notes())).'</td></tr>'; echo '</tbody></table></div>'; }
	private function render_plan_notice( $result ): void { if(!is_array($result)){return;} if(!empty($result['success'])){ $url=admin_url('admin.php?page='.Admin_Menu::LIBRARY_SLUG.'&library_view=detail&item_id='.absint($result['library_item_id'])); echo '<div class="notice notice-success is-dismissible"><p>'.esc_html($result['message_public']).' <a href="'.esc_url($url).'">'.esc_html__('Back to Library','ob-engine').'</a></p></div>'; } else { echo '<div class="notice notice-error is-dismissible"><p>'.esc_html($result['message_public'] ?? __('Auto Post plan generation failed.','ob-engine')).'</p></div>'; } }

	private function render_mapping_section( int $selected_preview_id, $mapping_plan, $mapping_result ): void { $items=(new Library_Repository())->query(array('type'=>Library_Type::SOURCE_PREVIEW,'limit'=>20)); echo '<div class="ob-engine-card"><h2>'.esc_html__('Mapping + Validation','ob-engine').'</h2><p>'.esc_html__('Map redacted source preview fields to generic OBE target fields. This does not generate content or write WordPress posts.','ob-engine').'</p><form method="post" action="">'; wp_nonce_field(self::MAPPING_NONCE_ACTION,self::MAPPING_NONCE_NAME); echo '<input type="hidden" name="obe_field_mapping_action" value="suggest" /><p><label for="obe-source-preview-id">'.esc_html__('Source Preview','ob-engine').'</label> <select id="obe-source-preview-id" name="obe_field_mapping[source_preview_library_item_id]">'; foreach($items as $item){ $label=$item->get_title(); if(''!==$item->get_source_label()){$label.=' — '.$item->get_source_label();} if(''!==$item->get_updated_at()){$label.=' — '.$item->get_updated_at();} echo '<option value="'.esc_attr((string)$item->get_id()).'" '.selected($selected_preview_id,$item->get_id(),false).'>'.esc_html($label).'</option>'; } echo '</select> <button type="submit" class="button button-secondary">'.esc_html__('Generate mapping suggestions','ob-engine').'</button></p></form>'; if($mapping_plan instanceof Field_Mapping_Plan){ $this->render_mapping_form($mapping_plan); } echo '</div>'; }
	private function render_mapping_form( Field_Mapping_Plan $plan ): void { echo '<h3>'.esc_html__('Validation status','ob-engine').': <span class="ob-engine-badge">'.esc_html($plan->get_validation_status()).'</span></h3>'; if($plan->get_missing_required_targets()){echo '<p><strong>'.esc_html__('Missing required targets','ob-engine').':</strong> '.esc_html(implode(', ',$plan->get_missing_required_targets())).'</p>';} if($plan->get_warnings()){echo '<ul>'; foreach($plan->get_warnings() as $warning){echo '<li>'.esc_html($warning).'</li>';} echo '</ul>';} echo '<form method="post" action="">'; wp_nonce_field(self::MAPPING_NONCE_ACTION,self::MAPPING_NONCE_NAME); echo '<input type="hidden" name="obe_field_mapping_action" value="save" /><input type="hidden" name="obe_field_mapping[source_preview_library_item_id]" value="'.esc_attr((string)$plan->get_source_preview_library_item_id()).'" /><input type="hidden" name="obe_field_mapping[source_label]" value="'.esc_attr($plan->get_source_label()).'" /><table class="widefat striped"><thead><tr><th>'.esc_html__('Source field','ob-engine').'</th><th>'.esc_html__('Redacted sample','ob-engine').'</th><th>'.esc_html__('Target field','ob-engine').'</th><th>'.esc_html__('Required','ob-engine').'</th><th>'.esc_html__('Notes','ob-engine').'</th></tr></thead><tbody>'; foreach($plan->get_mappings() as $i=>$m){ echo '<tr><td>'.esc_html($m->get_source_field()).'<input type="hidden" name="obe_field_mapping[mappings]['.esc_attr((string)$i).'][source_field]" value="'.esc_attr($m->get_source_field()).'" /></td><td>'.esc_html($m->get_sample_value_redacted()).'<input type="hidden" name="obe_field_mapping[mappings]['.esc_attr((string)$i).'][sample_value_redacted]" value="'.esc_attr($m->get_sample_value_redacted()).'" /></td><td><select name="obe_field_mapping[mappings]['.esc_attr((string)$i).'][target_field]">'; foreach(Field_Target::labels() as $target=>$label){echo '<option value="'.esc_attr($target).'" '.selected($m->get_target_field(),$target,false).'>'.esc_html($label).'</option>'; } echo '</select></td><td><label><input type="checkbox" name="obe_field_mapping[mappings]['.esc_attr((string)$i).'][required]" value="1" '.checked($m->is_required(),true,false).' /> '.esc_html__('Required','ob-engine').'</label></td><td><input type="text" name="obe_field_mapping[mappings]['.esc_attr((string)$i).'][notes]" value="'.esc_attr($m->get_notes()).'" /></td></tr>'; } echo '</tbody></table><p class="submit"><button type="submit" class="button button-primary">'.esc_html__('Validate and save mapping','ob-engine').'</button></p></form>'; }
	private function render_mapping_notice( $result ): void { if(!is_array($result)){return;} if(!empty($result['success'])){ $url=admin_url('admin.php?page='.Admin_Menu::LIBRARY_SLUG.'&library_view=detail&item_id='.absint($result['library_item_id'])); echo '<div class="notice notice-success is-dismissible"><p>'.esc_html($result['message_public']).' <a href="'.esc_url($url).'">'.esc_html__('Back to Library','ob-engine').'</a></p></div>'; } else { echo '<div class="notice notice-error is-dismissible"><p>'.esc_html($result['message_public'] ?? __('Field mapping failed.','ob-engine')).'</p></div>'; } }
	private function render_notices( $result ): void { if ( ! is_array( $result ) ) { return; } if ( ! empty( $result['success'] ) ) { $url = admin_url( 'admin.php?page=' . Admin_Menu::LIBRARY_SLUG . '&library_view=detail&item_id=' . absint( $result['library_item_id'] ) ); echo '<div class="notice notice-success is-dismissible"><p>' . esc_html( $result['message_public'] ) . ' <a href="' . esc_url( $url ) . '">' . esc_html__( 'View Library item', 'ob-engine' ) . '</a></p></div>'; return; } echo '<div class="notice notice-error is-dismissible"><p>' . esc_html( isset( $result['message_public'] ) ? $result['message_public'] : __( 'Source preview failed.', 'ob-engine' ) ) . '</p></div>'; }
	private function render_preview_card( Source_Preview $preview ): void { echo '<div class="ob-engine-card"><h2>' . esc_html__( 'Preview summary', 'ob-engine' ) . '</h2>'; echo '<p>' . esc_html( $preview->get_summary() ) . '</p><table class="widefat striped"><tbody>'; echo '<tr><th>' . esc_html__( 'Source type', 'ob-engine' ) . '</th><td>' . esc_html( Source_Type::label( $preview->get_source_type() ) ) . '</td></tr>'; echo '<tr><th>' . esc_html__( 'Item count', 'ob-engine' ) . '</th><td>' . esc_html( (string) $preview->get_item_count() ) . '</td></tr>'; echo '<tr><th>' . esc_html__( 'Column count', 'ob-engine' ) . '</th><td>' . esc_html( (string) $preview->get_column_count() ) . '</td></tr>'; echo '<tr><th>' . esc_html__( 'Columns', 'ob-engine' ) . '</th><td>' . esc_html( implode( ', ', $preview->get_columns() ) ) . '</td></tr>'; echo '<tr><th>' . esc_html__( 'Warnings', 'ob-engine' ) . '</th><td>' . esc_html( $preview->get_warnings() ? implode( '; ', $preview->get_warnings() ) : __( 'None', 'ob-engine' ) ) . '</td></tr>'; echo '</tbody></table></div>'; }
	private function default_form_data(): array { return array( 'source_label' => '', 'source_type' => 'auto', 'source_input' => '' ); }
	private function posted_data(): array { $raw = isset( $_POST['obe_source_preview'] ) && is_array( $_POST['obe_source_preview'] ) ? wp_unslash( $_POST['obe_source_preview'] ) : array(); return array_merge( $this->default_form_data(), $raw ); }
	private function posted_mapping_data(): array { $raw = isset( $_POST['obe_field_mapping'] ) && is_array( $_POST['obe_field_mapping'] ) ? wp_unslash( $_POST['obe_field_mapping'] ) : array(); return is_array($raw) ? $raw : array(); }
	private function posted_plan_data(): array { $raw = isset( $_POST['obe_auto_post_plan'] ) && is_array( $_POST['obe_auto_post_plan'] ) ? wp_unslash( $_POST['obe_auto_post_plan'] ) : array(); return is_array($raw) ? $raw : array(); }
	private function posted_draft_data(): array { $raw = isset( $_POST['obe_auto_post_draft'] ) && is_array( $_POST['obe_auto_post_draft'] ) ? wp_unslash( $_POST['obe_auto_post_draft'] ) : array(); return is_array($raw) ? $raw : array(); }
}
