<?php
/** Editorial Humanizer admin page. */
namespace OBEngine\Admin;
use OBEngine\Editorial\Editorial_Humanizer_Service; use OBEngine\Editorial\Editorial_Tone; use OBEngine\Library\Library_Repository; use OBEngine\Library\Library_Type; use OBEngine\Support\Capabilities; use OBEngine\Support\View;
defined( 'ABSPATH' ) || exit;
final class Editorial_Humanizer_Page {
	public function render(): void { if ( ! current_user_can( Capabilities::MANAGE ) ) { wp_die( esc_html__( 'You do not have permission to manage OBE.', 'ob-engine' ) ); } $result=null; $selected=isset($_GET['source_library_item_id'])?absint($_GET['source_library_item_id']):0; if ( 'POST' === ($_SERVER['REQUEST_METHOD']??'') && isset($_POST['obe_editorial_humanizer_nonce']) ) { check_admin_referer('obe_editorial_humanizer_generate','obe_editorial_humanizer_nonce'); $selected=isset($_POST['source_library_item_id'])?absint($_POST['source_library_item_id']):0; $result=(new Editorial_Humanizer_Service())->create_revision(array('source_library_item_id'=>$selected,'tone'=>isset($_POST['tone'])?sanitize_key((string)$_POST['tone']):Editorial_Tone::NATURAL,'editorial_notes'=>isset($_POST['editorial_notes'])?sanitize_textarea_field((string)$_POST['editorial_notes']):'')); } echo '<div class="wrap ob-engine-wrap ob-engine-page-default">'; View::heading( __( 'Humanizer', 'ob-engine' ) ); echo '<div class="notice notice-info inline"><p>'.esc_html__( 'Editorial Humanizer improves readability, tone, localization, and clarity. It does not publish or write WordPress posts.', 'ob-engine' ).'</p></div>'; echo '<div class="notice notice-warning inline"><p>'.esc_html__( 'This is not an AI-detection bypass tool. Outputs require human review.', 'ob-engine' ).'</p></div>'; if ( is_array($result) ) { $this->render_result($result); } $this->render_form($selected); echo '</div>'; }
	private function render_form( int $selected ): void { $repository=new Library_Repository(); $items=array_merge($repository->query(array('type'=>Library_Type::CONTENT_DRAFT,'limit'=>50)),$repository->query(array('type'=>Library_Type::EDITORIAL_REVISION,'limit'=>50))); echo '<div class="ob-engine-card"><h2>'.esc_html__( 'Generate revision', 'ob-engine' ).'</h2><form method="post">'; wp_nonce_field('obe_editorial_humanizer_generate','obe_editorial_humanizer_nonce'); echo '<table class="form-table"><tr><th scope="row"><label for="source_library_item_id">'.esc_html__( 'Source Library draft', 'ob-engine' ).'</label></th><td><select id="source_library_item_id" name="source_library_item_id" required><option value="">'.esc_html__( 'Select a Library draft', 'ob-engine' ).'</option>'; foreach($items as $item){ echo '<option value="'.esc_attr($item->get_id()).'" '.selected($selected,$item->get_id(),false).'>'.esc_html($item->get_title()).'</option>'; } echo '</select></td></tr><tr><th scope="row"><label for="tone">'.esc_html__( 'Tone', 'ob-engine' ).'</label></th><td><select id="tone" name="tone">'; foreach(Editorial_Tone::all() as $tone){ echo '<option value="'.esc_attr($tone).'">'.esc_html(Editorial_Tone::label($tone)).' — '.esc_html(Editorial_Tone::description($tone)).'</option>'; } echo '</select></td></tr><tr><th scope="row"><label for="editorial_notes">'.esc_html__( 'Editorial notes', 'ob-engine' ).'</label></th><td><textarea id="editorial_notes" name="editorial_notes" rows="5" class="large-text"></textarea><p class="description">'.esc_html__( 'Optional plain-text guidance. Do not include secrets or private data.', 'ob-engine' ).'</p></td></tr></table>'; submit_button( __( 'Generate revision and save to Library', 'ob-engine' ) ); echo '<p><a class="button" href="'.esc_url(admin_url('admin.php?page=ob-engine-library')).'">'.esc_html__( 'View Library', 'ob-engine' ).'</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=ob-engine-addons')).'">'.esc_html__( 'View Addons', 'ob-engine' ).'</a></p></form></div>'; }
	private function render_result( array $result ): void { if ( empty($result['success']) ) { echo '<div class="notice notice-error inline"><p>'.esc_html($result['message_public']??__( 'Action failed.', 'ob-engine' )).'</p></div>'; return; } $revision=$result['revision']; $data=$revision->to_array(); echo '<div class="notice notice-success inline"><p>'.esc_html($result['message_public']).' <a href="'.esc_url(admin_url('admin.php?page=ob-engine-library&library_view=detail&item_id='.(int)$result['library_item_id'])).'">'.esc_html__( 'Back to Library', 'ob-engine' ).'</a></p></div><div class="ob-engine-card"><h2>'.esc_html__( 'Revision summary', 'ob-engine' ).'</h2><ul><li><strong>'.esc_html__( 'Tone', 'ob-engine' ).':</strong> '.esc_html(Editorial_Tone::label($revision->get_tone())).'</li><li><strong>'.esc_html__( 'Revised title', 'ob-engine' ).':</strong> '.esc_html($revision->get_revised_title()).'</li><li><strong>'.esc_html__( 'Excerpt', 'ob-engine' ).':</strong> '.esc_html($revision->get_revised_excerpt()).'</li><li><strong>'.esc_html__( 'Readability score', 'ob-engine' ).':</strong> '.esc_html((string)$data['readability_score']).'</li><li><strong>'.esc_html__( 'Tone score', 'ob-engine' ).':</strong> '.esc_html((string)$data['tone_score']).'</li><li><strong>'.esc_html__( 'Localization score', 'ob-engine' ).':</strong> '.esc_html((string)$data['localization_score']).'</li><li><strong>'.esc_html__( 'Safety notes', 'ob-engine' ).':</strong> '.esc_html(implode('; ',$revision->get_safety_notes())).'</li></ul></div>'; }
}
