<?php
/** Activity item value object. @package OBEngine\Activity */
namespace OBEngine\Activity;
defined( 'ABSPATH' ) || exit;
final class Activity_Item {
	private $id; private $event_id; private $action; private $status; private $object_type; private $object_id; private $object_label; private $actor_id; private $message; private $context_redacted; private $created_at;
	public function __construct( array $data ) { $this->id=isset($data['id'])?absint($data['id']):0; $this->event_id=isset($data['event_id'])?(string)$data['event_id']:''; $this->action=isset($data['action'])&&Activity_Action::is_valid((string)$data['action'])?(string)$data['action']:Activity_Action::UNKNOWN; $this->status=isset($data['status'])&&Activity_Status::is_valid((string)$data['status'])?(string)$data['status']:Activity_Status::INFO; $this->object_type=isset($data['object_type'])&&Activity_Object_Type::is_valid((string)$data['object_type'])?(string)$data['object_type']:Activity_Object_Type::UNKNOWN; $this->object_id=isset($data['object_id'])?absint($data['object_id']):0; $this->object_label=isset($data['object_label'])?(string)$data['object_label']:''; $this->actor_id=isset($data['actor_id'])?absint($data['actor_id']):0; $this->message=isset($data['message'])?(string)$data['message']:''; $this->context_redacted=isset($data['context_redacted'])?$data['context_redacted']:array(); $this->created_at=isset($data['created_at'])?(string)$data['created_at']:''; }
	public static function from_row( $row ): self { return new self( is_array($row) ? $row : (array) $row ); }
	public function to_array(): array { return array( 'id'=>$this->id, 'event_id'=>$this->event_id, 'action'=>$this->action, 'status'=>$this->status, 'object_type'=>$this->object_type, 'object_id'=>$this->object_id, 'object_label'=>$this->object_label, 'actor_id'=>$this->actor_id, 'message'=>$this->message, 'context_redacted'=>$this->get_context_redacted(), 'created_at'=>$this->created_at ); }
	public function get_id(): int { return $this->id; } public function get_event_id(): string { return $this->event_id; } public function get_action(): string { return $this->action; } public function get_status(): string { return $this->status; } public function get_object_type(): string { return $this->object_type; } public function get_object_id(): int { return $this->object_id; } public function get_object_label(): string { return $this->object_label; } public function get_actor_id(): int { return $this->actor_id; } public function get_message(): string { return $this->message; } public function get_created_at(): string { return $this->created_at; }
	public function get_context_redacted(): array { if ( is_array( $this->context_redacted ) ) { return $this->context_redacted; } if ( is_string( $this->context_redacted ) && '' !== $this->context_redacted ) { $decoded = json_decode( $this->context_redacted, true ); return is_array( $decoded ) ? $decoded : array(); } return array(); }
}
