<?php
/** Activity admin page. @package OBEngine\Activity */
namespace OBEngine\Activity;
use OBEngine\Admin\Admin_Menu;
use OBEngine\Support\Capabilities;
use OBEngine\Support\View;
defined( 'ABSPATH' ) || exit;
final class Activity_Admin_Page {
	private $repository;
	public function __construct( ?Activity_Repository $repository = null ) { $this->repository = $repository ?: new Activity_Repository(); }
	public function render(): void { if ( ! current_user_can( Capabilities::MANAGE ) ) { wp_die( esc_html__( 'You do not have permission to view Activity.', 'ob-engine' ) ); } $this->repository->maybe_create_table(); echo '<div class="wrap ob-engine-wrap ob-engine-activity-wrap">'; View::heading( __( 'Activity', 'ob-engine' ) ); echo '<div class="notice notice-info inline"><p>' . esc_html__( 'Activity records redacted OBE events for review, troubleshooting, and auditability.', 'ob-engine' ) . '</p></div>'; $id = isset($_GET['activity_id']) ? absint($_GET['activity_id']) : 0; if ( $id ) { $this->render_detail( $this->repository->get($id) ); } else { $this->render_list(); } echo '</div>'; }
	private function render_list(): void { $filter = isset($_GET['activity_filter']) ? sanitize_key((string)$_GET['activity_filter']) : 'all'; $args = $this->filter_args($filter); $items = $this->repository->query($args); $this->filter_tabs($filter); echo '<table class="widefat striped ob-engine-activity-table"><thead><tr><th>' . esc_html__('Time','ob-engine') . '</th><th>' . esc_html__('Actor','ob-engine') . '</th><th>' . esc_html__('Action','ob-engine') . '</th><th>' . esc_html__('Object','ob-engine') . '</th><th>' . esc_html__('Status','ob-engine') . '</th><th>' . esc_html__('Details','ob-engine') . '</th></tr></thead><tbody>'; if ( empty($items) ) { echo '<tr><td colspan="6">' . esc_html__('No activity yet. Start with a dry-run or save a plan to Library.','ob-engine') . '</td></tr>'; } foreach ( $items as $item ) { $actor = $item->get_actor_id() ? get_the_author_meta( 'display_name', $item->get_actor_id() ) : __( 'System', 'ob-engine' ); $object = Activity_Object_Type::label($item->get_object_type()) . ( $item->get_object_label() ? ': ' . $item->get_object_label() : '' ); echo '<tr><td>' . esc_html($item->get_created_at()) . '</td><td>' . esc_html($actor) . '</td><td>' . esc_html(Activity_Action::label($item->get_action())) . '</td><td>' . esc_html($object) . '</td><td><span class="' . esc_attr(Activity_Status::badge_class($item->get_status())) . '">' . esc_html(Activity_Status::label($item->get_status())) . '</span></td><td><a href="' . esc_url($this->url(array('activity_id'=>$item->get_id(),'activity_filter'=>$filter))) . '">' . esc_html__('View','ob-engine') . '</a></td></tr>'; } echo '</tbody></table>'; }
	private function render_detail( $item ): void { echo '<p><a class="button" href="' . esc_url($this->url()) . '">' . esc_html__('Back to Activity','ob-engine') . '</a></p>'; if ( ! $item ) { echo '<div class="notice notice-error"><p>' . esc_html__('Activity event not found.','ob-engine') . '</p></div>'; return; } $actor = $item->get_actor_id() ? get_the_author_meta( 'display_name', $item->get_actor_id() ) : __( 'System', 'ob-engine' ); echo '<div class="ob-engine-card"><h2>' . esc_html(Activity_Action::label($item->get_action())) . ' <span class="' . esc_attr(Activity_Status::badge_class($item->get_status())) . '">' . esc_html(Activity_Status::label($item->get_status())) . '</span></h2><p class="ob-engine-meta">' . esc_html($item->get_created_at()) . '</p></div>'; echo '<div class="ob-engine-detail-grid"><div class="ob-engine-card"><h2>' . esc_html__('Actor','ob-engine') . '</h2><p>' . esc_html($actor) . '</p></div><div class="ob-engine-card"><h2>' . esc_html__('Object','ob-engine') . '</h2><p>' . esc_html(Activity_Object_Type::label($item->get_object_type())) . '</p><p>' . esc_html($item->get_object_label()) . '</p></div><div class="ob-engine-card"><h2>' . esc_html__('Message','ob-engine') . '</h2><p>' . esc_html($item->get_message()) . '</p></div><div class="ob-engine-card"><h2>' . esc_html__('Redacted context','ob-engine') . '</h2><pre class="ob-engine-activity-context">' . esc_html(wp_json_encode($item->get_context_redacted(), JSON_PRETTY_PRINT)) . '</pre></div></div>'; }
	private function filter_tabs( string $current ): void { $tabs=array('all'=>__('All','ob-engine'),'settings'=>__('Settings','ob-engine'),'provider'=>__('Provider','ob-engine'),'ai'=>__('AI','ob-engine'),'library'=>__('Library','ob-engine'),'workflow'=>__('Workflow','ob-engine'),'auto_post'=>__('Auto Post','ob-engine'),'errors'=>__('Errors','ob-engine')); echo '<nav class="nav-tab-wrapper ob-engine-filter-tabs">'; foreach ( $tabs as $key=>$label ) { echo '<a class="nav-tab ' . ( $current===$key ? 'nav-tab-active' : '' ) . '" href="' . esc_url($this->url(array('activity_filter'=>$key))) . '">' . esc_html($label) . '</a>'; } echo '</nav>'; }
	private function filter_args( string $filter ): array { if ( 'errors' === $filter ) { return array('status'=>Activity_Status::FAILED,'limit'=>50); } $map=array('settings'=>Activity_Object_Type::SETTINGS,'provider'=>Activity_Object_Type::PROVIDER,'library'=>Activity_Object_Type::LIBRARY_ITEM,'workflow'=>Activity_Object_Type::WORKFLOW,'auto_post'=>Activity_Object_Type::AUTO_POST); if ( isset($map[$filter]) ) { return array('object_type'=>$map[$filter],'limit'=>50); } if ( 'ai' === $filter ) { return array('search'=>'ai','limit'=>50); } return array('limit'=>50); }
	private function url( array $args = array() ): string { return add_query_arg( array_filter( array_merge( array( 'page' => Admin_Menu::ACTIVITY_SLUG ), $args ), static function( $value ) { return '' !== $value && null !== $value; } ), admin_url( 'admin.php' ) ); }
}
