<?php
/** Activity log repository. @package OBEngine\Activity */
namespace OBEngine\Activity;
use WP_Error;
defined( 'ABSPATH' ) || exit;
final class Activity_Repository {
	public function table_name(): string { global $wpdb; return $wpdb->prefix . 'obe_activity_log'; }
	public function create_table(): void { global $wpdb; $charset_collate = $wpdb->get_charset_collate(); $table = $this->table_name(); $sql = "CREATE TABLE {$table} ( id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, event_id VARCHAR(64) NOT NULL, action VARCHAR(100) NOT NULL, status VARCHAR(40) NOT NULL, object_type VARCHAR(80) NOT NULL, object_id BIGINT UNSIGNED NOT NULL DEFAULT 0, object_label VARCHAR(191) NOT NULL DEFAULT '', actor_id BIGINT UNSIGNED NOT NULL DEFAULT 0, message TEXT NULL, context_redacted LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY  (id), KEY event_id (event_id), KEY action (action), KEY status (status), KEY object_type_object_id (object_type, object_id), KEY created_at (created_at) ) {$charset_collate};"; if ( ! function_exists( 'dbDelta' ) ) { require_once ABSPATH . 'wp-admin/includes/upgrade.php'; } dbDelta( $sql ); }
	public function table_exists(): bool { global $wpdb; $table = $this->table_name(); return $table === $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) ); }
	public function maybe_create_table(): void { if ( ! $this->table_exists() ) { $this->create_table(); } }
	public function insert( array $data ) { global $wpdb; $data = $this->sanitize_activity_data( $data ); $result = $wpdb->insert( $this->table_name(), $data, array( '%s','%s','%s','%s','%d','%s','%d','%s','%s','%s' ) ); if ( false === $result ) { return new WP_Error( 'obe_activity_insert_failed', __( 'Activity entry could not be saved.', 'ob-engine' ) ); } return (int) $wpdb->insert_id; }
	public function get( int $id ) { global $wpdb; $row = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . $this->table_name() . ' WHERE id = %d', absint( $id ) ) ); return $row ? Activity_Item::from_row( $row ) : null; }
	public function query( array $args = array() ): array { global $wpdb; $where = $this->where_sql( $args ); $limit = isset($args['limit']) ? max(1,min(100,absint($args['limit']))) : 20; $paged = isset($args['paged']) ? max(1,absint($args['paged'])) : 1; $offset = ($paged-1)*$limit; $sql = 'SELECT * FROM ' . $this->table_name() . $where['sql'] . ' ORDER BY created_at DESC, id DESC LIMIT %d OFFSET %d'; $params = array_merge( $where['params'], array( $limit, $offset ) ); $rows = $wpdb->get_results( $wpdb->prepare( $sql, $params ) ); return array_map( static function( $row ) { return Activity_Item::from_row( $row ); }, is_array($rows)?$rows:array() ); }
	public function count( array $args = array() ): int { global $wpdb; $where = $this->where_sql( $args ); $sql = 'SELECT COUNT(*) FROM ' . $this->table_name() . $where['sql']; return (int) $wpdb->get_var( $where['params'] ? $wpdb->prepare( $sql, $where['params'] ) : $sql ); }
	public function sanitize_activity_data( array $data ): array { $action = isset($data['action']) ? sanitize_key((string)$data['action']) : Activity_Action::UNKNOWN; $status = isset($data['status']) ? sanitize_key((string)$data['status']) : Activity_Status::INFO; $object_type = isset($data['object_type']) ? sanitize_key((string)$data['object_type']) : Activity_Object_Type::UNKNOWN; $redactor = new Activity_Redactor(); return array( 'event_id' => ! empty($data['event_id']) ? sanitize_text_field((string)$data['event_id']) : ( function_exists('wp_generate_uuid4') ? wp_generate_uuid4() : uniqid('obe_', true) ), 'action' => Activity_Action::is_valid($action) ? $action : Activity_Action::UNKNOWN, 'status' => Activity_Status::is_valid($status) ? $status : Activity_Status::INFO, 'object_type' => Activity_Object_Type::is_valid($object_type) ? $object_type : Activity_Object_Type::UNKNOWN, 'object_id' => isset($data['object_id']) ? absint($data['object_id']) : 0, 'object_label' => isset($data['object_label']) ? sanitize_text_field((string)$data['object_label']) : '', 'actor_id' => isset($data['actor_id']) ? absint($data['actor_id']) : ( function_exists('get_current_user_id') ? absint(get_current_user_id()) : 0 ), 'message' => isset($data['message']) ? sanitize_textarea_field((string)$data['message']) : '', 'context_redacted' => $redactor->to_json( isset($data['context']) && is_array($data['context']) ? $data['context'] : array() ), 'created_at' => isset($data['created_at']) ? sanitize_text_field((string)$data['created_at']) : ( function_exists('current_time') ? current_time('mysql') : gmdate('Y-m-d H:i:s') ), ); }
	private function where_sql( array $args ): array { global $wpdb; $where=array(); $params=array(); foreach ( array('action','status','object_type') as $field ) { if ( ! empty($args[$field]) ) { $where[] = "$field = %s"; $params[] = sanitize_key((string)$args[$field]); } } if ( isset($args['object_id']) && '' !== $args['object_id'] ) { $where[]='object_id = %d'; $params[]=absint($args['object_id']); } if ( ! empty($args['search']) ) { $like = '%' . $wpdb->esc_like( sanitize_text_field((string)$args['search']) ) . '%'; $where[]='(action LIKE %s OR object_label LIKE %s OR message LIKE %s)'; $params[]=$like; $params[]=$like; $params[]=$like; } return array( 'sql' => $where ? ' WHERE ' . implode(' AND ', $where) : '', 'params' => $params ); }
}
