<?php
/** Static workflow visualizer graph. @package OBEngine\Workflow */
namespace OBEngine\Workflow;
use OBEngine\Library\Library_Type;
defined( 'ABSPATH' ) || exit;
final class Workflow_Graph {
	public function nodes(): array { $rows=array(
		array('id'=>'source_preview','label'=>'Source Preview','description'=>'Preview redacted source intake.','input'=>'Pasted generic source data.','output'=>'Private Library source preview.','library_type'=>Library_Type::SOURCE_PREVIEW,'requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>false,'risk_level'=>'low','activity_events'=>array('source_preview_created'),'gate_notes'=>array('Review source summary before mapping.')),
		array('id'=>'field_mapping','label'=>'Field Mapping','description'=>'Map source fields to generic OBE fields.','input'=>'Source Preview.','output'=>'Validated field mapping.','library_type'=>Library_Type::FIELD_MAPPING,'requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>false,'risk_level'=>'low','activity_events'=>array('field_mapping_saved'),'gate_notes'=>array('Mapping requires review before planning.')),
		array('id'=>'auto_post_plan','label'=>'Auto Post Plan','description'=>'Generate review-first content plan after explicit admin action.','input'=>'Validated Field Mapping.','output'=>'Auto Post Plan Library item.','library_type'=>Library_Type::AUTO_POST_PLAN,'requires_human_review'=>true,'calls_ai_provider'=>true,'writes_wordpress'=>false,'risk_level'=>'medium','activity_events'=>array('auto_post_plan_generated'),'gate_notes'=>array('Explicit admin action: Generate plan.')),
		array('id'=>'draft_candidate','label'=>'Draft Candidate','description'=>'Generate a review-first content draft candidate.','input'=>'Approved Auto Post Plan.','output'=>'Content Draft Library item.','library_type'=>Library_Type::CONTENT_DRAFT,'requires_human_review'=>true,'calls_ai_provider'=>true,'writes_wordpress'=>false,'risk_level'=>'medium','activity_events'=>array('auto_post_draft_generated'),'gate_notes'=>array('Explicit admin action; saved to Library only.')),
		array('id'=>'editorial_humanizer','label'=>'Editorial Humanizer','description'=>'Generate editorial revision candidate for readability review.','input'=>'Eligible Library draft.','output'=>'Editorial Revision Library item.','library_type'=>Library_Type::EDITORIAL_REVISION,'requires_human_review'=>true,'calls_ai_provider'=>true,'writes_wordpress'=>false,'risk_level'=>'medium','activity_events'=>array('editorial_revision_generated'),'gate_notes'=>array('Explicit admin action; saved to Library only.')),
		array('id'=>'library_review','label'=>'Library','description'=>'Review stored private Library items.','input'=>'Generated or preview Library items.','output'=>'Reviewed Library item.','library_type'=>'','requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>false,'risk_level'=>'low','activity_events'=>array('library_item_reviewed'),'gate_notes'=>array('Review before approval.')),
		array('id'=>'approval','label'=>'Approval','description'=>'Approve writeable Library items only.','input'=>'Content Draft or Editorial Revision.','output'=>'Approval record.','library_type'=>'','requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>false,'risk_level'=>'medium','activity_events'=>array('library_item_approved'),'gate_notes'=>array('Approval record must be approved.')),
		array('id'=>'dry_run','label'=>'Dry-run','description'=>'Validate target before any WordPress write.','input'=>'Approved writeable Library item.','output'=>'Passed dry-run result.','library_type'=>'','requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>false,'risk_level'=>'medium','activity_events'=>array('wordpress_write_planned'),'gate_notes'=>array('Latest dry-run must pass.')),
		array('id'=>'write_draft','label'=>'Write Draft','description'=>'Controlled WordPress draft write path.','input'=>'Approved item with passed dry-run.','output'=>'WordPress draft or needs_review post.','library_type'=>Library_Type::CONTENT_DRAFT,'requires_human_review'=>true,'calls_ai_provider'=>false,'writes_wordpress'=>true,'risk_level'=>'high','activity_events'=>array('wordpress_draft_written'),'gate_notes'=>array('Human review required.','Approval required.','Dry-run required.','Publish is rejected.')),
	); return array_map(array('OBEngine\\Workflow\\Workflow_Node','from_array'),$rows); }
	public function edges(): array { $rows=array(array('from'=>'source_preview','to'=>'field_mapping','label'=>'Source Preview → Field Mapping','gate'=>'Review'),array('from'=>'field_mapping','to'=>'auto_post_plan','label'=>'Field Mapping → Auto Post Plan','gate'=>'Generate plan'),array('from'=>'auto_post_plan','to'=>'draft_candidate','label'=>'Auto Post Plan → Draft Candidate','gate'=>'Review'),array('from'=>'draft_candidate','to'=>'editorial_humanizer','label'=>'Draft Candidate → Editorial Humanizer','gate'=>'Review'),array('from'=>'editorial_humanizer','to'=>'library_review','label'=>'Editorial Humanizer → Library Review','gate'=>'Save to Library'),array('from'=>'library_review','to'=>'approval','label'=>'Library Review → Approval','gate'=>'Review'),array('from'=>'approval','to'=>'dry_run','label'=>'Approval → Dry-run','gate'=>'Run dry-run'),array('from'=>'dry_run','to'=>'write_draft','label'=>'Dry-run → Write Draft','gate'=>'Write draft')); return array_map(function($r){return new Workflow_Edge($r);},$rows); }
	public function to_array(): array { return array('nodes'=>array_map(function($n){return $n->to_array();},$this->nodes()),'edges'=>array_map(function($e){return $e->to_array();},$this->edges())); }
	public function to_json(): string { return function_exists('wp_json_encode') ? wp_json_encode($this->to_array(), JSON_PRETTY_PRINT) : json_encode($this->to_array(), JSON_PRETTY_PRINT); }
	public function validate(): array { $errors=array(); $nodes=$this->nodes(); $ids=array(); $write=0; foreach($nodes as $n){$ids[$n->get_id()]=true; if($n->writes_wordpress()){$write++;}} foreach($this->edges() as $e){ if(empty($ids[$e->get_from()])||empty($ids[$e->get_to()])){$errors[]='Edge references unknown node.';} } if(1!==$write){$errors[]='Exactly one write node is required.';} $by=array(); foreach($nodes as $n){$by[$n->get_id()]=$n->to_array(); if($n->calls_ai_provider() && false===strpos(implode(' ', $n->to_array()['gate_notes']),'Explicit admin action')){$errors[]='AI node must require explicit admin action.';} } if(empty($by['write_draft']['requires_human_review']) || false===strpos(implode(' ', $by['write_draft']['gate_notes']),'Approval') || false===strpos(implode(' ', $by['write_draft']['gate_notes']),'Dry-run')){$errors[]='write_draft must require human review, approval, and dry-run.';} foreach(array('source_preview','field_mapping','auto_post_plan') as $id){ if(!empty($by[$id]['writes_wordpress'])){$errors[]=$id.' must not write.';} } return $errors; }
	public function risk_summary(): array { $out=array('low'=>0,'medium'=>0,'high'=>0); foreach($this->nodes() as $n){ $r=$n->get_risk_level(); $out[$r]=isset($out[$r])?$out[$r]+1:1; } return $out; }
}
