<?php
/** Addon registry. */
namespace OBEngine\Addons;
use OBEngine\Addons\AutoPost\Auto_Post_Addon;
defined( 'ABSPATH' ) || exit;
final class Addon_Registry {
	private $addons;
	public function all(): array { if ( null === $this->addons ) { $this->addons = $this->apply_filters_to_addons( $this->register_builtin_addons() ); uasort( $this->addons, static function ( Addon_Definition $a, Addon_Definition $b ) { $ad = $a->to_array(); $bd = $b->to_array(); return $ad['order'] <=> $bd['order']; } ); } return $this->addons; }
	public function enabled(): array { return array_filter( $this->all(), static function ( Addon_Definition $addon ) { return $addon->is_enabled(); } ); }
	public function get( string $addon_id ) { $id = sanitize_key( $addon_id ); $addons = $this->all(); return $addons[ $id ] ?? null; }
	public function has( string $addon_id ): bool { return $this->get( $addon_id ) instanceof Addon_Definition; }
	public function register_builtin_addons(): array { return array( 'auto_post' => Auto_Post_Addon::definition(), 'seo_review' => new Addon_Definition( array( 'id' => 'seo_review', 'name' => __( 'SEO Review', 'ob-engine' ), 'description' => __( 'Reviews content metadata and suggests safe improvements. Runtime is not included yet.', 'ob-engine' ), 'status' => Addon_Status::COMING_SOON, 'scope' => Addon_Scope::COMMUNITY, 'primary_action' => __( 'Preview', 'ob-engine' ), 'secondary_action' => __( 'Save to Library', 'ob-engine' ), 'order' => 20 ) ), 'performance_review' => new Addon_Definition( array( 'id' => 'performance_review', 'name' => __( 'Performance Review', 'ob-engine' ), 'description' => __( 'Reviews performance signals without modifying server files. Runtime is not included yet.', 'ob-engine' ), 'status' => Addon_Status::COMING_SOON, 'scope' => Addon_Scope::COMMUNITY, 'primary_action' => __( 'Preview', 'ob-engine' ), 'secondary_action' => __( 'Review', 'ob-engine' ), 'order' => 30 ) ), 'translation_plan' => new Addon_Definition( array( 'id' => 'translation_plan', 'name' => __( 'Translation Plan', 'ob-engine' ), 'description' => __( 'Plans translations and review queues without live autonomous translation. Runtime is not included yet.', 'ob-engine' ), 'status' => Addon_Status::COMING_SOON, 'scope' => Addon_Scope::COMMUNITY, 'primary_action' => __( 'Generate plan', 'ob-engine' ), 'secondary_action' => __( 'Review', 'ob-engine' ), 'order' => 40 ) ), 'workflow_pro' => new Addon_Definition( array( 'id' => 'workflow_pro', 'name' => __( 'Workflow Pro', 'ob-engine' ), 'description' => __( 'Advanced workflow executor preview. No Pro/private executor ships in Community.', 'ob-engine' ), 'status' => Addon_Status::PRO, 'scope' => Addon_Scope::PRO, 'primary_action' => __( 'Preview', 'ob-engine' ), 'secondary_action' => __( 'Review', 'ob-engine' ), 'order' => 50 ) ), 'private_project_adapter' => new Addon_Definition( array( 'id' => 'private_project_adapter', 'name' => __( 'Private Project Adapter', 'ob-engine' ), 'description' => __( 'Private adapters are not included in the public repository or Community runtime.', 'ob-engine' ), 'status' => Addon_Status::PRO, 'scope' => Addon_Scope::PRIVATE_ADAPTER, 'primary_action' => __( 'Preview only', 'ob-engine' ), 'secondary_action' => __( 'Not included', 'ob-engine' ), 'order' => 60 ) ) ); }
	public function apply_filters_to_addons( array $addons ): array { $filtered = function_exists( 'apply_filters' ) ? apply_filters( 'ob_engine_addons', $addons ) : $addons; $normalized = array(); foreach ( $filtered as $key => $addon ) { if ( is_array( $addon ) ) { $addon = new Addon_Definition( $addon ); } if ( $addon instanceof Addon_Definition && '' !== $addon->get_id() ) { $normalized[ $addon->get_id() ] = $addon; } } return $normalized; }
}
