<?php
/** Field mapping validator. @package OBEngine\Sources */
namespace OBEngine\Sources;
defined( 'ABSPATH' ) || exit;
final class Field_Mapping_Validator {
	public function validate( Field_Mapping_Plan $plan ): Field_Mapping_Plan { $missing=$this->missing_required_targets($plan); $warnings=$this->warnings_for_plan($plan); $status=$this->validation_status($plan,$warnings,$missing); $data=$plan->to_array(); $data['missing_required_targets']=$missing; $data['warnings']=$warnings; $data['validation_status']=$status; $data['summary']=sprintf('Field mapping validation %s with %d mappings, %d warning(s), and %d missing required target(s).',$status,count($plan->get_mappings()),count($warnings),count($missing)); return new Field_Mapping_Plan($data); }
	public function missing_required_targets( Field_Mapping_Plan $plan ): array { $targets=array(); foreach($plan->get_mappings() as $m){ if(!$m->is_ignored()){$targets[]=$m->get_target_field();} } $missing=array(); if(!in_array(Field_Target::TITLE,$targets,true)){$missing[]=Field_Target::TITLE;} if(!in_array(Field_Target::CONTENT,$targets,true) && !in_array(Field_Target::SUMMARY,$targets,true)){$missing[]=Field_Target::CONTENT;} return $missing; }
	public function duplicate_targets( Field_Mapping_Plan $plan ): array { $ignore=array(Field_Target::NOTES,Field_Target::TAGS,Field_Target::CUSTOM_FIELD,Field_Target::IGNORE); $seen=array(); $dupes=array(); foreach($plan->get_mappings() as $m){ $target=$m->get_target_field(); if(in_array($target,$ignore,true)){continue;} if(isset($seen[$target])){$dupes[$target]=$target;} $seen[$target]=true; } return array_values($dupes); }
	public function warnings_for_plan( Field_Mapping_Plan $plan ): array { $warnings=array(); foreach($this->duplicate_targets($plan) as $target){$warnings[]=sprintf('Duplicate mapping target: %s.', Field_Target::label($target));} $notes=0; foreach($plan->get_mappings() as $m){ if($m->is_required() && $m->is_ignored()){$warnings[]=sprintf('Required source field ignored: %s.', $m->get_source_field());} if(Field_Target::NOTES===$m->get_target_field()){$notes++;} } if($notes >= 4){$warnings[]='Many source fields are mapped to Notes. Review mappings before generation.';} return $warnings; }
	public function validation_status( Field_Mapping_Plan $plan, array $warnings, array $missing_required ): string { if(!empty($missing_required)){return 'failed';} return !empty($warnings) ? 'warning' : 'passed'; }
}
