<?php
/** Field mapping plan value object. @package OBEngine\Sources */
namespace OBEngine\Sources;
defined( 'ABSPATH' ) || exit;
final class Field_Mapping_Plan {
	private $source_preview_library_item_id; private $source_label; private $source_type; private $mappings; private $required_targets; private $missing_required_targets; private $warnings; private $validation_status; private $summary; private $created_at;
	public function __construct( array $data = array() ) { $this->source_preview_library_item_id = isset($data['source_preview_library_item_id']) ? absint($data['source_preview_library_item_id']) : 0; $this->source_label = isset($data['source_label']) ? sanitize_text_field((string)$data['source_label']) : ''; $this->source_type = isset($data['source_type']) ? sanitize_key((string)$data['source_type']) : ''; $this->mappings = $this->normalize_mappings($data['mappings'] ?? array()); $this->required_targets = $this->normalize_targets($data['required_targets'] ?? Field_Target::required_for_basic_post()); $this->missing_required_targets = $this->normalize_targets($data['missing_required_targets'] ?? array()); $this->warnings = $this->normalize_strings($data['warnings'] ?? array()); $status = isset($data['validation_status']) ? sanitize_key((string)$data['validation_status']) : 'not_checked'; $this->validation_status = in_array($status,array('not_checked','passed','warning','failed'),true) ? $status : 'not_checked'; $this->summary = isset($data['summary']) ? sanitize_textarea_field((string)$data['summary']) : $this->build_summary(); $this->created_at = isset($data['created_at']) ? sanitize_text_field((string)$data['created_at']) : gmdate('c'); }
	public static function empty(): self { return new self(); }
	public function to_array(): array { return array('source_preview_library_item_id'=>$this->source_preview_library_item_id,'source_label'=>$this->source_label,'source_type'=>$this->source_type,'mappings'=>array_map(static function($m){return $m->to_array();},$this->mappings),'required_targets'=>$this->required_targets,'missing_required_targets'=>$this->missing_required_targets,'warnings'=>$this->warnings,'validation_status'=>$this->validation_status,'summary'=>$this->summary,'created_at'=>$this->created_at); }
	public function get_source_preview_library_item_id(): int { return $this->source_preview_library_item_id; } public function get_source_label(): string { return $this->source_label; } public function get_source_type(): string { return $this->source_type; } public function get_mappings(): array { return $this->mappings; } public function get_required_targets(): array { return $this->required_targets; } public function get_missing_required_targets(): array { return $this->missing_required_targets; } public function get_warnings(): array { return $this->warnings; } public function get_validation_status(): string { return $this->validation_status; } public function get_summary(): string { return $this->summary; } public function is_valid_for_basic_post(): bool { return in_array($this->validation_status,array('passed','warning'),true) && empty($this->missing_required_targets); }
	private function normalize_mappings( $items ): array { $out=array(); if(!is_array($items)){return $out;} foreach($items as $item){ if($item instanceof Field_Mapping_Item){$out[]=$item;} elseif(is_array($item)){$out[]=Field_Mapping_Item::from_array($item);} } return $out; }
	private function normalize_targets( $items ): array { $out=array(); if(!is_array($items)){return $out;} foreach($items as $item){ $target=sanitize_key((string)$item); if(Field_Target::is_valid($target) && !in_array($target,$out,true)){$out[]=$target;} } return $out; }
	private function normalize_strings( $items ): array { $out=array(); if(!is_array($items)){return $out;} foreach($items as $item){ $value=sanitize_text_field((string)$item); if(''!==$value){$out[]=$value;} } return $out; }
	private function build_summary(): string { return sprintf('Field mapping plan with %d mapped source fields. Validation status: %s.', count($this->mappings), $this->validation_status); }
}
