<?php
/** Field mapping service. @package OBEngine\Sources */
namespace OBEngine\Sources;
use OBEngine\Activity\Activity_Action; use OBEngine\Activity\Activity_Logger; use OBEngine\Activity\Activity_Object_Type; use OBEngine\Library\Library_Repository; use OBEngine\Library\Library_Status; use OBEngine\Library\Library_Type;
defined( 'ABSPATH' ) || exit;
final class Field_Mapping_Service {
	private $library_repository; private $validator; private $logger; private $redactor;
	public function __construct( Library_Repository $library_repository = null, Field_Mapping_Validator $validator = null, Activity_Logger $logger = null ) { $this->library_repository=$library_repository ?: new Library_Repository(); $this->validator=$validator ?: new Field_Mapping_Validator(); $this->logger=$logger ?: new Activity_Logger(); $this->redactor=new Source_Preview_Redactor(); }
	public function build_suggested_plan_from_source_preview( int $source_preview_library_item_id ): Field_Mapping_Plan { $payload=$this->extract_preview_payload($source_preview_library_item_id); $columns=$this->extract_columns_from_preview_payload($payload); $samples=$this->extract_sample_values_from_preview_payload($payload); $mappings=array(); foreach($columns as $column){ $target=Field_Target::suggested_target_for_source_column($column); $mappings[]=new Field_Mapping_Item(array('source_field'=>$column,'target_field'=>$target,'required'=>in_array($target,array(Field_Target::TITLE,Field_Target::CONTENT,Field_Target::SUMMARY),true),'sample_value_redacted'=>$samples[$column] ?? '','notes'=>'')); } $plan=new Field_Mapping_Plan(array('source_preview_library_item_id'=>$source_preview_library_item_id,'source_label'=>$payload['source_label'] ?? '','source_type'=>$payload['source_type'] ?? '','mappings'=>$mappings)); return $this->validator->validate($plan); }
	public function save_mapping_plan( array $data ) { $validation=$this->validate_data($data); if(!empty($validation['errors'])){ return array('success'=>false,'plan'=>Field_Mapping_Plan::empty(),'message_public'=>implode(' ',$validation['errors'])); } $base=$this->extract_preview_payload($validation['data']['source_preview_library_item_id']); $plan=new Field_Mapping_Plan(array('source_preview_library_item_id'=>$validation['data']['source_preview_library_item_id'],'source_label'=>$validation['data']['source_label'] ?: ($base['source_label'] ?? ''),'source_type'=>$base['source_type'] ?? '','mappings'=>$validation['data']['mappings'])); $plan=$this->validator->validate($plan); $library_data=$this->build_library_data($plan,$validation['data']); $id=$this->library_repository->create($library_data); if(function_exists('is_wp_error') && is_wp_error($id)){ return array('success'=>false,'plan'=>$plan,'message_public'=>__('Field mapping plan could not be saved to Library.','ob-engine')); } $status = 'failed' === $plan->get_validation_status() ? 'warning' : ('warning' === $plan->get_validation_status() ? 'warning' : 'success'); $log_data=array('object_type'=>Activity_Object_Type::FIELD_MAPPING,'object_id'=>(int)$id,'object_label'=>$plan->get_source_label(),'message'=>'Field mapping plan saved to Library.','context'=>array('source_preview_library_item_id'=>$plan->get_source_preview_library_item_id(),'mapping_library_item_id'=>(int)$id,'source_type'=>$plan->get_source_type(),'source_label_present'=>''!==$plan->get_source_label(),'mappings_count'=>count($plan->get_mappings()),'required_targets_count'=>count($plan->get_required_targets()),'missing_required_targets_count'=>count($plan->get_missing_required_targets()),'warnings_count'=>count($plan->get_warnings()),'validation_status'=>$plan->get_validation_status())); if('success'===$status){$this->logger->success(Activity_Action::FIELD_MAPPING_CREATED,$log_data);} else {$this->logger->warning(Activity_Action::FIELD_MAPPING_CREATED,$log_data);} return array('success'=>true,'library_item_id'=>(int)$id,'plan'=>$plan,'message_public'=>__('Field mapping plan saved to Library.','ob-engine')); }
	public function validate_data( array $data ): array { $id=isset($data['source_preview_library_item_id']) ? absint($data['source_preview_library_item_id']) : 0; $errors=array(); if($id<=0){$errors[]=__('Source Preview is required.','ob-engine');} $raw=isset($data['mappings']) && is_array($data['mappings']) ? $data['mappings'] : array(); if(empty($raw)){$errors[]=__('At least one mapping is required.','ob-engine');} $mappings=array(); foreach($raw as $row){ if(is_array($row)){$mappings[]=Field_Mapping_Item::from_array($row);} } return array('errors'=>$errors,'data'=>array('source_preview_library_item_id'=>$id,'source_label'=>isset($data['source_label'])?sanitize_text_field((string)$data['source_label']):'','mappings'=>$mappings)); }
	public function extract_preview_payload( int $source_preview_library_item_id ): array { $item=$this->library_repository->get($source_preview_library_item_id); if(!$item || Library_Type::SOURCE_PREVIEW !== $item->get_type()){return array();} $payload=json_decode($item->get_payload_redacted(),true); return is_array($payload) ? $payload : array(); }
	public function extract_columns_from_preview_payload( array $payload ): array { $columns=isset($payload['columns']) && is_array($payload['columns']) ? $payload['columns'] : array(); return array_values(array_filter(array_map('sanitize_text_field',$columns))); }
	public function extract_sample_values_from_preview_payload( array $payload ): array { $samples=array(); $rows=isset($payload['sample_rows']) && is_array($payload['sample_rows']) ? $payload['sample_rows'] : array(); foreach($rows as $row){ if(!is_array($row)){continue;} foreach($row as $key=>$value){ $field=sanitize_text_field((string)$key); if(''!==$field && !isset($samples[$field])){$samples[$field]=$this->redactor->redact_value(is_scalar($value)?(string)$value:'[REDACTED_PRIVATE_PAYLOAD]');} } } return $samples; }
	public function build_library_data( Field_Mapping_Plan $plan, array $data ): array { $label=$plan->get_source_label() ?: __('Source Preview','ob-engine'); $content=$this->build_content($plan); $status = 'failed' === $plan->get_validation_status() && Library_Status::is_valid(Library_Status::FAILED) ? Library_Status::FAILED : Library_Status::NEEDS_REVIEW; return array('title'=>sprintf('Field Mapping: %s',$label),'type'=>Library_Type::FIELD_MAPPING,'status'=>$status,'source_label'=>$label,'summary'=>$plan->get_summary(),'content'=>$content,'payload_redacted'=>$this->mapping_payload_redacted($plan),'created_context'=>'field_mapping_validation'); }
	public function mapping_payload_redacted( Field_Mapping_Plan $plan ): string { $json=wp_json_encode($plan->to_array()); return is_string($json)?$json:'{}'; }
	private function build_content( Field_Mapping_Plan $plan ): string { $lines=array('Validation status: '.$plan->get_validation_status(),'Source preview Library item: '.$plan->get_source_preview_library_item_id(),'Mappings:'); foreach($plan->get_mappings() as $m){$lines[]='- '.$m->get_source_field().' => '.Field_Target::label($m->get_target_field());} if($plan->get_missing_required_targets()){$lines[]='Missing required targets: '.implode(', ',$plan->get_missing_required_targets());} if($plan->get_warnings()){$lines[]='Warnings: '.implode('; ',$plan->get_warnings());} $lines[]='Mapping and validation only: no AI provider call, content generation, WordPress post write, or publish action was performed.'; return implode("\n",$lines); }
}
