<?php
/** Source preview parser. @package OBEngine\Sources */
namespace OBEngine\Sources;
defined( 'ABSPATH' ) || exit;
final class Source_Preview_Parser {
	private const MAX_INPUT = 20000; private const MAX_ROWS = 10; private const MAX_COLUMNS = 30;
	private $redactor;
	public function __construct( ?Source_Preview_Redactor $redactor = null ) { $this->redactor = $redactor ?: new Source_Preview_Redactor(); }
	public function parse( array $data ): Source_Preview { $input = isset( $data['source_input'] ) ? (string) $data['source_input'] : ''; $label = isset( $data['source_label'] ) ? (string) $data['source_label'] : ''; $requested = isset( $data['source_type'] ) ? (string) $data['source_type'] : ''; $warnings = array(); if ( strlen( $input ) > self::MAX_INPUT ) { $input = substr( $input, 0, self::MAX_INPUT ); $warnings[] = 'Input was truncated for preview.'; } $type = $this->detect_type( $input, $requested ); $preview = Source_Type::CSV_TEXT === $type ? $this->parse_csv_text( $input, $label ) : ( Source_Type::JSON_TEXT === $type ? $this->parse_json_text( $input, $label ) : ( Source_Type::MANUAL_ITEM === $type ? $this->parse_manual_item( $input, $label ) : $this->parse_plain_text( $input, $label ) ) ); if ( $warnings ) { $array = $preview->to_array(); $array['warnings'] = array_merge( $warnings, $array['warnings'] ); $array['summary'] = $this->summarize_preview( $array['source_type'], (int) $array['item_count'], (array) $array['columns'], (array) $array['warnings'] ); return new Source_Preview( $array ); } return $preview; }
	public function parse_csv_text( string $input, string $source_label = '' ): Source_Preview { $lines = preg_split( '/\r\n|\r|\n/', trim( $input ) ); $rows = array(); foreach ( $lines as $line ) { if ( '' === trim( $line ) ) { continue; } $rows[] = str_getcsv( $line ); } $warnings = array(); $columns = array(); $data_rows = $rows; if ( isset( $rows[0] ) && count( $rows[0] ) > 1 ) { $columns = array_slice( array_map( 'strval', $rows[0] ), 0, self::MAX_COLUMNS ); $data_rows = array_slice( $rows, 1 ); } $sample = array(); foreach ( array_slice( $data_rows, 0, self::MAX_ROWS ) as $row ) { $assoc = array(); foreach ( array_slice( $row, 0, self::MAX_COLUMNS ) as $index => $value ) { $key = $columns[ $index ] ?? 'column_' . ( $index + 1 ); $assoc[ $key ] = $value; } $sample[] = $assoc; } if ( count( $columns ) >= self::MAX_COLUMNS ) { $warnings[] = 'Columns were limited for preview.'; } $sample = $this->redactor->redact_rows( $sample ); return $this->make_preview( Source_Type::CSV_TEXT, $source_label, count( $data_rows ), $columns, $sample, $warnings ); }
	public function parse_json_text( string $input, string $source_label = '' ): Source_Preview { $decoded = json_decode( $input, true ); if ( JSON_ERROR_NONE !== json_last_error() ) { $preview = $this->parse_plain_text( $input, $source_label ); $array = $preview->to_array(); $array['warnings'][] = 'Invalid JSON; plain text preview was used.'; $array['summary'] = $this->summarize_preview( $array['source_type'], (int) $array['item_count'], (array) $array['columns'], (array) $array['warnings'] ); return new Source_Preview( $array ); } $items = $this->is_list( $decoded ) ? $decoded : array( $decoded ); $columns = array(); $sample = array(); foreach ( $items as $item ) { if ( ! is_array( $item ) ) { $item = array( 'value' => $item ); } foreach ( array_keys( $item ) as $key ) { if ( ! in_array( $key, $columns, true ) && count( $columns ) < self::MAX_COLUMNS ) { $columns[] = (string) $key; } } if ( count( $sample ) < self::MAX_ROWS ) { $sample[] = $item; } } return $this->make_preview( Source_Type::JSON_TEXT, $source_label, count( $items ), $columns, $this->redactor->redact_rows( $sample ), array() ); }
	public function parse_plain_text( string $input, string $source_label = '' ): Source_Preview { $lines = preg_split( '/\r\n|\r|\n/', trim( $input ) ); $non_empty = array_values( array_filter( $lines, static function ( $line ) { return '' !== trim( (string) $line ); } ) ); $sample = array( array( 'excerpt' => $this->redactor->redact_value( implode( "\n", array_slice( $non_empty, 0, self::MAX_ROWS ) ) ), 'line_count' => count( $non_empty ), 'character_count' => strlen( $input ) ) ); return $this->make_preview( Source_Type::PASTE_TEXT, $source_label, count( $non_empty ), array( 'excerpt', 'line_count', 'character_count' ), $sample, array() ); }
	public function parse_manual_item( string $input, string $source_label = '' ): Source_Preview { $lines = preg_split( '/\r\n|\r|\n/', trim( $input ) ); $sample = array(); foreach ( $lines as $line ) { if ( '' === trim( $line ) ) { continue; } $parts = preg_split( '/\s*[:=]\s*/', $line, 2 ); $sample[] = 2 === count( $parts ) ? array( 'field' => $parts[0], 'value' => $parts[1] ) : array( 'note' => $line ); if ( count( $sample ) >= self::MAX_ROWS ) { break; } } return $this->make_preview( Source_Type::MANUAL_ITEM, $source_label, count( array_filter( $lines ) ), array( 'field', 'value', 'note' ), $this->redactor->redact_rows( $sample ), array() ); }
	public function detect_type( string $input, string $requested_type = '' ): string { if ( Source_Type::is_valid( $requested_type ) ) { return $requested_type; } $trim = trim( $input ); if ( '' !== $trim && in_array( $trim[0], array( '{', '[' ), true ) ) { return Source_Type::JSON_TEXT; } $first = strtok( $trim, "\r\n" ); if ( false !== $first && false !== strpos( $first, ',' ) ) { return Source_Type::CSV_TEXT; } return Source_Type::PASTE_TEXT; }
	public function summarize_preview( string $source_type, int $item_count, array $columns, array $warnings = array() ): string { return sprintf( '%s preview with %d item(s), %d column(s), and %d warning(s).', Source_Type::label( $source_type ), $item_count, count( $columns ), count( $warnings ) ); }
	private function make_preview( string $type, string $label, int $count, array $columns, array $sample, array $warnings ): Source_Preview { $columns = array_slice( array_values( $columns ), 0, self::MAX_COLUMNS ); return new Source_Preview( array( 'source_type' => $type, 'source_label' => $label, 'item_count' => $count, 'column_count' => count( $columns ), 'columns' => $columns, 'sample_rows' => $sample, 'summary' => $this->summarize_preview( $type, $count, $columns, $warnings ), 'warnings' => $warnings, 'payload_redacted' => array( 'sample_rows' => $sample, 'columns' => $columns, 'limits' => array( 'sample_rows' => self::MAX_ROWS, 'columns' => self::MAX_COLUMNS, 'cell_length' => 240 ) ) ) ); }
	private function is_list( $value ): bool { return is_array( $value ) && array_keys( $value ) === range( 0, count( $value ) - 1 ); }
}
