<?php
/** Source intake service. @package OBEngine\Sources */
namespace OBEngine\Sources;
use OBEngine\Activity\Activity_Action;
use OBEngine\Activity\Activity_Logger;
use OBEngine\Activity\Activity_Object_Type;
use OBEngine\Library\Library_Repository;
use OBEngine\Library\Library_Status;
use OBEngine\Library\Library_Type;
defined( 'ABSPATH' ) || exit;
final class Source_Intake_Service {
	private $parser; private $library_repository; private $logger;
	public function __construct( Source_Preview_Parser $parser = null, Library_Repository $library_repository = null, Activity_Logger $logger = null ) { $this->parser = $parser ?: new Source_Preview_Parser(); $this->library_repository = $library_repository ?: new Library_Repository(); $this->logger = $logger ?: new Activity_Logger(); }
	public function create_preview( array $data ) { $validation = $this->validate_data( $data ); if ( ! empty( $validation['errors'] ) ) { $this->logger->failed( Activity_Action::SOURCE_PREVIEW_FAILED, array( 'object_type' => Activity_Object_Type::SOURCE_PREVIEW, 'message' => 'Source preview failed validation.', 'context' => array( 'source_type' => $validation['data']['source_type'], 'source_label_present' => '' !== $validation['data']['source_label'] ) ) ); return array( 'success' => false, 'preview' => Source_Preview::empty(), 'message_public' => implode( ' ', $validation['errors'] ) ); } $preview = $this->parser->parse( $validation['data'] ); $library_data = $this->build_library_data( $preview, $validation['data'] ); $id = $this->library_repository->create( $library_data ); if ( function_exists( 'is_wp_error' ) && is_wp_error( $id ) ) { $this->logger->failed( Activity_Action::SOURCE_PREVIEW_FAILED, array( 'object_type' => Activity_Object_Type::SOURCE_PREVIEW, 'message' => 'Source preview could not be saved.', 'context' => array( 'source_type' => $preview->get_source_type(), 'source_label_present' => '' !== $preview->get_source_label(), 'item_count' => $preview->get_item_count(), 'column_count' => $preview->get_column_count(), 'warnings_count' => count( $preview->get_warnings() ) ) ) ); return array( 'success' => false, 'preview' => $preview, 'message_public' => __( 'Source preview could not be saved to Library.', 'ob-engine' ) ); } $this->logger->success( Activity_Action::SOURCE_PREVIEW_CREATED, array( 'object_type' => Activity_Object_Type::SOURCE_PREVIEW, 'object_id' => (int) $id, 'object_label' => $preview->get_source_label(), 'message' => 'Source preview saved to Library.', 'context' => array( 'source_type' => $preview->get_source_type(), 'source_label_present' => '' !== $preview->get_source_label(), 'item_count' => $preview->get_item_count(), 'column_count' => $preview->get_column_count(), 'warnings_count' => count( $preview->get_warnings() ), 'library_item_id' => (int) $id ) ) ); return array( 'success' => true, 'library_item_id' => (int) $id, 'preview' => $preview, 'message_public' => __( 'Source preview saved to Library.', 'ob-engine' ) ); }
	public function validate_data( array $data ): array { $source_type = isset( $data['source_type'] ) ? sanitize_key( (string) $data['source_type'] ) : ''; $source_label = isset( $data['source_label'] ) ? sanitize_text_field( (string) $data['source_label'] ) : ''; $source_input = isset( $data['source_input'] ) ? sanitize_textarea_field( (string) $data['source_input'] ) : ''; $errors = array(); if ( '' === trim( $source_input ) ) { $errors[] = __( 'Source input is required.', 'ob-engine' ); } if ( '' !== $source_type && 'auto' !== $source_type && ! Source_Type::is_valid( $source_type ) ) { $errors[] = __( 'Source type is not supported.', 'ob-engine' ); $source_type = ''; } return array( 'errors' => $errors, 'data' => array( 'source_type' => $source_type, 'source_label' => $source_label, 'source_input' => $source_input ) ); }
	public function build_library_data( Source_Preview $preview, array $data ): array { $label = '' !== $preview->get_source_label() ? $preview->get_source_label() : ( isset( $data['source_label'] ) && '' !== (string) $data['source_label'] ? (string) $data['source_label'] : __( 'Manual Source', 'ob-engine' ) ); $content = $this->build_content( $preview ); return array( 'title' => sprintf( 'Source Preview: %s', $label ?: Source_Type::label( $preview->get_source_type() ) ), 'type' => Library_Type::SOURCE_PREVIEW, 'status' => Library_Status::NEEDS_REVIEW, 'source_label' => $label, 'summary' => $preview->get_summary(), 'content' => $content, 'payload_redacted' => $this->preview_payload_redacted( $preview ), 'created_context' => 'source_intake_preview' ); }
	public function preview_payload_redacted( Source_Preview $preview ): string { $json = wp_json_encode( $preview->to_array() ); return is_string( $json ) ? $json : '{}'; }
	private function build_content( Source_Preview $preview ): string { $lines = array(); $lines[] = 'Source type: ' . Source_Type::label( $preview->get_source_type() ); $lines[] = 'Item count: ' . $preview->get_item_count(); $lines[] = 'Column count: ' . $preview->get_column_count(); if ( $preview->get_columns() ) { $lines[] = 'Columns: ' . implode( ', ', $preview->get_columns() ); } if ( $preview->get_warnings() ) { $lines[] = 'Warnings: ' . implode( '; ', $preview->get_warnings() ); } $lines[] = 'Preview only: no generation, mapping, provider call, post write, or publish action was performed.'; return implode( "\n", $lines ); }
}
