<?php
/** Controlled WordPress draft writer. @package OBEngine\Writing */
namespace OBEngine\Writing;
use OBEngine\Safety\Safety_Result;
use OBEngine\Safety\Write_Target;
defined( 'ABSPATH' ) || exit;
final class WordPress_Draft_Writer {
	public function write( Write_Target $target ): Write_Result { $safety = $this->validate_target( $target ); if ( ! $safety->is_passed() ) { return Write_Result::failed( $safety->get_message(), array( 'status' => $safety->get_status(), 'blockers_count' => count( $safety->get_blockers() ), 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status() ) ); } if ( ! function_exists( 'wp_insert_post' ) ) { return Write_Result::failed( __( 'WordPress post insertion is unavailable.', 'ob-engine' ), array( 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status() ) ); } $post_data = array( 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status(), 'post_title' => $target->get_title(), 'post_content' => $target->get_content(), 'post_excerpt' => $target->get_excerpt(), 'meta_input' => array( '_obe_source_library_item_id' => $target->get_source_library_item_id(), '_obe_written_by_ob_engine' => '1', '_obe_write_created_at' => function_exists( 'current_time' ) ? current_time( 'mysql' ) : gmdate( 'Y-m-d H:i:s' ) ) ); if ( function_exists( 'get_current_user_id' ) && get_current_user_id() > 0 ) { $post_data['post_author'] = get_current_user_id(); } $id = wp_insert_post( $post_data, true ); if ( function_exists( 'is_wp_error' ) && is_wp_error( $id ) ) { return Write_Result::failed( $id->get_error_message(), array( 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status() ) ); } if ( ! $id ) { return Write_Result::failed( __( 'WordPress draft could not be created.', 'ob-engine' ), array( 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status() ) ); } return Write_Result::success( (int) $id, $target->get_post_type(), $target->get_post_status(), __( 'WordPress draft created from approved Library item.', 'ob-engine' ) ); }
	public function validate_target( Write_Target $target ): Safety_Result { $base = $target->validate(); if ( ! $base->is_passed() ) { return $base; } $blockers = array(); if ( ! in_array( $target->get_post_status(), $this->allowed_post_statuses(), true ) ) { $blockers[] = __( 'Target post status must be draft or pending.', 'ob-engine' ); } if ( ! in_array( $target->get_post_type(), $this->allowed_post_types(), true ) ) { $blockers[] = __( 'Target post type is not allowed for Write Draft.', 'ob-engine' ); } return $blockers ? Safety_Result::failed( __( 'Write target is not allowed.', 'ob-engine' ), $blockers, array( 'target_post_type' => $target->get_post_type(), 'target_post_status' => $target->get_post_status() ) ) : Safety_Result::passed( __( 'Write target is allowed.', 'ob-engine' ), array( 'target_post_type' => $target->get_post_type(), 'target_post_status' => $target->get_post_status() ) ); }
	public function allowed_post_statuses(): array { return array( Write_Target::STATUS_DRAFT, Write_Target::STATUS_PENDING ); }
	public function allowed_post_types(): array { if ( ! function_exists( 'get_post_types' ) || ! function_exists( 'post_type_exists' ) ) { return array( 'post' ); } $types = get_post_types( array( 'public' => true ), 'objects' ); $allowed = array(); foreach ( $types as $name => $object ) { if ( in_array( $name, array( 'attachment', 'revision', 'nav_menu_item', 'custom_css', 'customize_changeset', 'oembed_cache', 'user_request', 'wp_block', 'wp_template', 'wp_template_part', 'wp_navigation' ), true ) ) { continue; } if ( ! empty( $object->_builtin ) && 'post' !== $name && 'page' !== $name ) { continue; } if ( post_type_exists( $name ) ) { $allowed[] = $name; } } return $allowed ? $allowed : array( 'post' ); }
}
