<?php
/** Write record repository. @package OBEngine\Writing */
namespace OBEngine\Writing;
use OBEngine\Library\Library_Repository;
use WP_Error;
defined( 'ABSPATH' ) || exit;
final class Write_Repository {
	public const META_STATUS = '_obe_write_status'; public const META_POST_ID = '_obe_write_post_id'; public const META_POST_TYPE = '_obe_write_post_type'; public const META_POST_STATUS = '_obe_write_post_status'; public const META_ACTOR_ID = '_obe_write_actor_id'; public const META_ACTOR_LABEL = '_obe_write_actor_label'; public const META_SUMMARY = '_obe_write_summary'; public const META_RESULT_REDACTED = '_obe_write_result_redacted'; public const META_CREATED_AT = '_obe_write_created_at'; public const META_UPDATED_AT = '_obe_write_updated_at';
	public function get( int $library_item_id ): Write_Record { if ( ! $this->is_library_item( $library_item_id ) ) { return Write_Record::empty_for_item( $library_item_id ); } return Write_Record::from_meta( $library_item_id, get_post_meta( $library_item_id ) ); }
	public function save( int $library_item_id, Write_Record $record ) { if ( ! $this->is_library_item( $library_item_id ) ) { return new WP_Error( 'obe_write_invalid_item', __( 'Invalid Library item.', 'ob-engine' ) ); } $data = $this->sanitize_record_data( $record->to_array() ); update_post_meta( $library_item_id, self::META_STATUS, $data['status'] ); update_post_meta( $library_item_id, self::META_POST_ID, $data['post_id'] ); update_post_meta( $library_item_id, self::META_POST_TYPE, $data['post_type'] ); update_post_meta( $library_item_id, self::META_POST_STATUS, $data['post_status'] ); update_post_meta( $library_item_id, self::META_ACTOR_ID, $data['actor_id'] ); update_post_meta( $library_item_id, self::META_ACTOR_LABEL, $data['actor_label'] ); update_post_meta( $library_item_id, self::META_SUMMARY, $data['summary'] ); update_post_meta( $library_item_id, self::META_RESULT_REDACTED, wp_json_encode( $data['result_redacted'] ) ); update_post_meta( $library_item_id, self::META_CREATED_AT, $data['created_at'] ); update_post_meta( $library_item_id, self::META_UPDATED_AT, $data['updated_at'] ); return true; }
	public function mark_written( int $library_item_id, Write_Result $result ) { return $this->save_result( $library_item_id, $result, Write_Status::WRITTEN ); }
	public function mark_failed( int $library_item_id, Write_Result $result ) { return $this->save_result( $library_item_id, $result, Write_Status::FAILED ); }
	public function sanitize_record_data( array $data ): array { return ( new Write_Record( $data ) )->to_array(); }
	private function save_result( int $library_item_id, Write_Result $result, string $status ) { $now = function_exists( 'current_time' ) ? current_time( 'mysql' ) : gmdate( 'Y-m-d H:i:s' ); $actor_id = function_exists( 'get_current_user_id' ) ? get_current_user_id() : 0; $record = new Write_Record( array( 'library_item_id' => $library_item_id, 'status' => $status, 'post_id' => $result->get_post_id(), 'post_type' => $result->get_post_type(), 'post_status' => $result->get_post_status(), 'actor_id' => $actor_id, 'actor_label' => $this->current_actor_label(), 'summary' => $result->get_message(), 'result_redacted' => $result->get_result_redacted(), 'created_at' => $result->get_created_at(), 'updated_at' => $now ) ); return $this->save( $library_item_id, $record ); }
	private function is_library_item( int $library_item_id ): bool { return $library_item_id > 0 && function_exists( 'get_post_type' ) && Library_Repository::POST_TYPE === get_post_type( $library_item_id ) && ( ! function_exists( 'get_post_status' ) || 'private' === get_post_status( $library_item_id ) ); }
	private function current_actor_label(): string { if ( function_exists( 'wp_get_current_user' ) ) { $user = wp_get_current_user(); if ( $user && ! empty( $user->display_name ) ) { return sanitize_text_field( $user->display_name ); } } return __( 'Unknown user', 'ob-engine' ); }
}
