<?php
/** Write Draft service. @package OBEngine\Writing */
namespace OBEngine\Writing;
use OBEngine\Activity\Activity_Action;
use OBEngine\Activity\Activity_Logger;
use OBEngine\Activity\Activity_Object_Type;
use OBEngine\Approval\Approval_Repository;
use OBEngine\Approval\Approval_Status;
use OBEngine\Library\Library_Item;
use OBEngine\Library\Library_Repository;
use OBEngine\Library\Library_Status;
use OBEngine\Library\Library_Type;
use OBEngine\Safety\Dry_Run_Repository;
use OBEngine\Safety\Safety_Result;
use OBEngine\Safety\Safety_Status;
use OBEngine\Safety\Write_Target;
use WP_Error;
defined( 'ABSPATH' ) || exit;
final class Write_Draft_Service {
	private $library_repository; private $approval_repository; private $dry_run_repository; private $write_repository; private $writer; private $logger;
	public function __construct( Library_Repository $library_repository = null, Approval_Repository $approval_repository = null, Dry_Run_Repository $dry_run_repository = null, Write_Repository $write_repository = null, WordPress_Draft_Writer $writer = null, Activity_Logger $logger = null ) { $this->library_repository = $library_repository ?: new Library_Repository(); $this->approval_repository = $approval_repository ?: new Approval_Repository( $this->library_repository ); $this->dry_run_repository = $dry_run_repository ?: new Dry_Run_Repository(); $this->write_repository = $write_repository ?: new Write_Repository(); $this->writer = $writer ?: new WordPress_Draft_Writer(); $this->logger = $logger ?: new Activity_Logger(); }
	public function write_from_library_item( int $library_item_id, array $target_data = array() ) { $item = $this->library_repository->get( $library_item_id ); if ( ! $item ) { return new WP_Error( 'obe_write_missing_item', __( 'Library item not found.', 'ob-engine' ) ); } $eligibility = $this->can_write( $item ); if ( ! $eligibility->is_passed() ) { $result = Write_Result::failed( $eligibility->get_message(), array( 'status' => $eligibility->get_status(), 'blockers_count' => count( $eligibility->get_blockers() ) ) ); $this->write_repository->mark_failed( $item->get_id(), $result ); $this->log_failed( $item, $result ); return $result; } $target = $this->build_target( $item, $target_data ); $result = $this->writer->write( $target ); if ( $result->is_success() ) { if ( function_exists( 'update_post_meta' ) ) { update_post_meta( $result->get_post_id(), '_obe_source_library_item_id', $item->get_id() ); } $this->write_repository->mark_written( $item->get_id(), $result ); $this->library_repository->update_status( $item->get_id(), Library_Status::WRITTEN ); $this->log_success( $item, $result ); } else { $this->write_repository->mark_failed( $item->get_id(), $result ); $this->log_failed( $item, $result ); } return $result; }
	public function can_write( Library_Item $item ): Safety_Result { if ( $item->get_id() <= 0 || ! function_exists( 'get_post_type' ) || Library_Repository::POST_TYPE !== get_post_type( $item->get_id() ) || ( function_exists( 'get_post_status' ) && 'private' !== get_post_status( $item->get_id() ) ) ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Only private OBE Library items can be written.', 'ob-engine' ) ) ); } if ( Library_Status::APPROVED !== $item->get_status() ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Library item status must be approved before writing a draft.', 'ob-engine' ) ), array( 'library_status' => $item->get_status() ) ); } if ( ! Library_Type::is_writeable( $item->get_type() ) ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Library item type is not writeable.', 'ob-engine' ) ), array( 'library_item_type' => $item->get_type() ) ); } if ( in_array( $item->get_status(), array( Library_Status::ARCHIVED, Library_Status::REJECTED, Library_Status::FAILED, Library_Status::WRITTEN ), true ) ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Archived, rejected, failed, or already written Library items cannot be written.', 'ob-engine' ) ) ); } $approval = $this->approval_repository->get( $item->get_id() ); if ( Approval_Status::APPROVED !== $approval->get_status() ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Library item must be approved before writing a draft.', 'ob-engine' ) ), array( 'approval_status' => $approval->get_status() ) ); } $dry_run = $this->dry_run_repository->get( $item->get_id() ); if ( ! $dry_run->is_passed() ) { return Safety_Result::failed( __( 'Write draft failed.', 'ob-engine' ), array( __( 'Latest dry-run must pass before writing a draft.', 'ob-engine' ) ), array( 'dry_run_status' => $dry_run->get_status() ) ); } return Safety_Result::passed( __( 'Library item can be written as a draft.', 'ob-engine' ), array( 'approval_status' => $approval->get_status(), 'dry_run_status' => $dry_run->get_status() ) ); }
	public function build_target( Library_Item $item, array $target_data = array() ): Write_Target { $dry_run = $this->dry_run_repository->get( $item->get_id() ); $stored = $dry_run->get_target(); $overrides = array( 'post_type' => isset( $stored['post_type'] ) ? sanitize_key( (string) $stored['post_type'] ) : 'post', 'post_status' => isset( $stored['post_status'] ) ? sanitize_key( (string) $stored['post_status'] ) : Write_Target::STATUS_DRAFT ); if ( isset( $target_data['post_type'] ) ) { $overrides['post_type'] = sanitize_key( (string) $target_data['post_type'] ); } if ( isset( $target_data['post_status'] ) ) { $overrides['post_status'] = sanitize_key( (string) $target_data['post_status'] ); } return Write_Target::from_library_item( $item, $overrides ); }
	public function build_success_context( Library_Item $item, Write_Result $result ): array { $approval = $this->approval_repository->get( $item->get_id() ); $dry_run = $this->dry_run_repository->get( $item->get_id() ); return array( 'library_item_id' => $item->get_id(), 'library_item_title' => $item->get_title(), 'library_item_type' => $item->get_type(), 'library_status_before' => $item->get_status(), 'approval_status' => $approval->get_status(), 'dry_run_status' => $dry_run->get_status(), 'post_id' => $result->get_post_id(), 'post_type' => $result->get_post_type(), 'post_status' => $result->get_post_status() ); }
	public function build_failed_context( Library_Item $item, Write_Result $result ): array { $context = $this->build_success_context( $item, $result ); $context['write_status'] = $result->get_status(); $context['write_message'] = $result->get_message(); return $context; }
	private function log_success( Library_Item $item, Write_Result $result ): void { $this->logger->success( Activity_Action::WORDPRESS_DRAFT_WRITTEN, array( 'object_type' => Activity_Object_Type::WORDPRESS_POST, 'object_id' => $result->get_post_id(), 'object_label' => $item->get_title(), 'message' => __( 'WordPress draft created from approved Library item.', 'ob-engine' ), 'context' => $this->build_success_context( $item, $result ) ) ); }
	private function log_failed( Library_Item $item, Write_Result $result ): void { $this->logger->failed( Activity_Action::SAFETY_CHECK_FAILED, array( 'object_type' => Activity_Object_Type::LIBRARY_ITEM, 'object_id' => $item->get_id(), 'object_label' => $item->get_title(), 'message' => __( 'Write draft failed.', 'ob-engine' ), 'context' => $this->build_failed_context( $item, $result ) ) ); }
}
