<?php
/** Write record value object. @package OBEngine\Writing */
namespace OBEngine\Writing;
defined( 'ABSPATH' ) || exit;
final class Write_Record {
	private $library_item_id; private $status; private $post_id; private $post_type; private $post_status; private $actor_id; private $actor_label; private $summary; private $result_redacted; private $created_at; private $updated_at;
	public function __construct( array $data ) { $status = isset( $data['status'] ) ? sanitize_key( (string) $data['status'] ) : Write_Status::NOT_WRITTEN; $this->library_item_id = isset( $data['library_item_id'] ) ? absint( $data['library_item_id'] ) : 0; $this->status = Write_Status::is_valid( $status ) ? $status : Write_Status::NOT_WRITTEN; $this->post_id = isset( $data['post_id'] ) ? absint( $data['post_id'] ) : 0; $this->post_type = isset( $data['post_type'] ) ? sanitize_key( (string) $data['post_type'] ) : ''; $this->post_status = isset( $data['post_status'] ) ? sanitize_key( (string) $data['post_status'] ) : ''; $this->actor_id = isset( $data['actor_id'] ) ? absint( $data['actor_id'] ) : 0; $this->actor_label = isset( $data['actor_label'] ) ? sanitize_text_field( (string) $data['actor_label'] ) : ''; $this->summary = isset( $data['summary'] ) ? sanitize_textarea_field( wp_strip_all_tags( (string) $data['summary'] ) ) : ''; $this->result_redacted = isset( $data['result_redacted'] ) && is_array( $data['result_redacted'] ) ? $this->sanitize_redacted( $data['result_redacted'] ) : array(); $this->created_at = isset( $data['created_at'] ) ? sanitize_text_field( (string) $data['created_at'] ) : ''; $this->updated_at = isset( $data['updated_at'] ) ? sanitize_text_field( (string) $data['updated_at'] ) : ''; }
	public static function empty_for_item( int $library_item_id ): self { return new self( array( 'library_item_id' => $library_item_id, 'status' => Write_Status::NOT_WRITTEN, 'summary' => __( 'No WordPress draft has been written yet.', 'ob-engine' ) ) ); }
	public static function from_meta( int $library_item_id, array $meta ): self { $value = static function( array $meta, string $key ) { if ( ! isset( $meta[ $key ] ) ) { return ''; } $raw = $meta[ $key ]; return is_array( $raw ) ? (string) reset( $raw ) : (string) $raw; }; $json = $value( $meta, '_obe_write_result_redacted' ); $redacted = $json ? json_decode( $json, true ) : array(); return new self( array( 'library_item_id' => $library_item_id, 'status' => $value( $meta, '_obe_write_status' ), 'post_id' => $value( $meta, '_obe_write_post_id' ), 'post_type' => $value( $meta, '_obe_write_post_type' ), 'post_status' => $value( $meta, '_obe_write_post_status' ), 'actor_id' => $value( $meta, '_obe_write_actor_id' ), 'actor_label' => $value( $meta, '_obe_write_actor_label' ), 'summary' => $value( $meta, '_obe_write_summary' ), 'result_redacted' => is_array( $redacted ) ? $redacted : array(), 'created_at' => $value( $meta, '_obe_write_created_at' ), 'updated_at' => $value( $meta, '_obe_write_updated_at' ) ) ); }
	public function to_array(): array { return array( 'library_item_id' => $this->library_item_id, 'status' => $this->status, 'post_id' => $this->post_id, 'post_type' => $this->post_type, 'post_status' => $this->post_status, 'actor_id' => $this->actor_id, 'actor_label' => $this->actor_label, 'summary' => $this->summary, 'result_redacted' => $this->result_redacted, 'created_at' => $this->created_at, 'updated_at' => $this->updated_at ); }
	public function get_library_item_id(): int { return $this->library_item_id; } public function get_status(): string { return $this->status; } public function get_post_id(): int { return $this->post_id; } public function get_post_type(): string { return $this->post_type; } public function get_post_status(): string { return $this->post_status; } public function get_actor_label(): string { return $this->actor_label; } public function get_summary(): string { return $this->summary; } public function get_result_redacted(): array { return $this->result_redacted; } public function is_written(): bool { return Write_Status::WRITTEN === $this->status; } public function is_failed(): bool { return Write_Status::FAILED === $this->status; }
	private function sanitize_redacted( array $data ): array { $clean = array(); foreach ( $data as $key => $value ) { $clean[ sanitize_key( (string) $key ) ] = is_array( $value ) ? $this->sanitize_redacted( $value ) : sanitize_text_field( (string) $value ); } return $clean; }
}
