<?php
/** Editorial Humanizer service. */
namespace OBEngine\Editorial;
use OBEngine\AI\AI_Engine; use OBEngine\AI\AI_Response; use OBEngine\AI\AI_Task_Type; use OBEngine\AI\Structured_Output; use OBEngine\Activity\Activity_Action; use OBEngine\Activity\Activity_Logger; use OBEngine\Activity\Activity_Object_Type; use OBEngine\Library\Library_Repository; use OBEngine\Library\Library_Status; use OBEngine\Library\Library_Type;
defined( 'ABSPATH' ) || exit;
final class Editorial_Humanizer_Service {
	private $engine; private $library_repository; private $logger;
	public function __construct( AI_Engine $engine = null, Library_Repository $library_repository = null, Activity_Logger $logger = null ) { $this->engine=$engine?:new AI_Engine(); $this->library_repository=$library_repository?:new Library_Repository(); $this->logger=$logger?:new Activity_Logger(); }
	public function create_revision( array $data ) { $valid=$this->validate_data($data); if ( ! $valid['success'] ) { return $valid; } $item=$this->load_source_library_item((int)$valid['source_library_item_id']); if ( ! $this->is_eligible_source_item($item) ) { return array('success'=>false,'message_public'=>__( 'Selected Library item is not eligible for editorial revision.', 'ob-engine' )); } $task=$this->build_ai_task_data($valid,$item); $response=$this->engine->run($task); $rdata=$response->to_array(); if ( ! $response->is_success() ) { $this->logger->failed(Activity_Action::EDITORIAL_REVISION_FAILED,array('object_type'=>Activity_Object_Type::EDITORIAL_REVISION,'object_id'=>$item->get_id(),'object_label'=>$item->get_title(),'message'=>'Editorial revision failed.','context'=>array('source_library_item_id'=>$item->get_id(),'tone'=>$valid['tone'],'request_id'=>$rdata['request_id']??''))); return array('success'=>false,'message_public'=>__( 'Editorial revision could not be generated. Check provider settings and try again.', 'ob-engine' )); } $revision=$this->build_editorial_revision($response,$valid,$item); if ( '' === trim( wp_strip_all_tags( $revision->get_revised_content() ) ) ) { return array('success'=>false,'message_public'=>__( 'Editorial revision did not include usable content.', 'ob-engine' )); } $created=$this->library_repository->create($this->build_library_data($revision,$valid)); if ( is_wp_error( $created ) || ! $created ) { return array('success'=>false,'message_public'=>__( 'Editorial revision could not be saved to Library.', 'ob-engine' )); } $this->logger->success(Activity_Action::EDITORIAL_REVISION_CREATED,array('object_type'=>Activity_Object_Type::EDITORIAL_REVISION,'object_id'=>(int)$created,'object_label'=>'Editorial Revision: '.$revision->get_revised_title(),'message'=>'Editorial revision saved to Library.','context'=>array('source_library_item_id'=>$item->get_id(),'editorial_revision_library_item_id'=>(int)$created,'tone'=>$revision->get_tone(),'provider'=>$rdata['provider']??'','model'=>$rdata['model']??'','request_id'=>$rdata['request_id']??'','has_output_json'=>!empty($rdata['output_json']),'has_output_text'=>!empty($rdata['output_text']),'default_status'=>$revision->get_default_status(),'revised_title_present'=>''!==$revision->get_revised_title()))); return array('success'=>true,'library_item_id'=>(int)$created,'revision'=>$revision,'message_public'=>__( 'Editorial revision saved to Library for human review.', 'ob-engine' )); }
	public function validate_data( array $data ): array { $id=isset($data['source_library_item_id'])?absint($data['source_library_item_id']):0; if ( $id < 1 ) { return array('success'=>false,'message_public'=>__( 'Source Library item is required.', 'ob-engine' )); } $tone=isset($data['tone'])?sanitize_key((string)$data['tone']):Editorial_Tone::NATURAL; if ( ! Editorial_Tone::is_valid($tone) ) { $tone=Editorial_Tone::NATURAL; } return array('success'=>true,'source_library_item_id'=>$id,'tone'=>$tone,'editorial_notes'=>isset($data['editorial_notes'])?sanitize_textarea_field((string)$data['editorial_notes']):''); }
	public function load_source_library_item( int $source_library_item_id ) { return $this->library_repository->get($source_library_item_id); }
	public function is_eligible_source_item( $library_item ): bool { return is_object($library_item) && method_exists($library_item,'get_type') && in_array($library_item->get_type(),array(Library_Type::CONTENT_DRAFT,Library_Type::EDITORIAL_REVISION),true); }
	public function build_ai_task_data( array $data, $library_item ): array { $tone_label=Editorial_Tone::label($data['tone']); $tone_description=Editorial_Tone::description($data['tone']); $tone_instruction='Apply the selected editorial tone: '.$tone_label.'. '.$tone_description; $base_instructions=''!==$data['editorial_notes']?$data['editorial_notes']:'Improve readability, clarity, localization, and tone while preserving meaning. Save for human review only; do not publish or write WordPress posts.'; $input=array('source_title'=>$library_item->get_title(),'source_content'=>wp_strip_all_tags($library_item->get_content()),'source_summary'=>$library_item->get_summary(),'selected_tone'=>$data['tone'],'selected_tone_label'=>$tone_label); return array('task_type'=>AI_Task_Type::EDITORIAL_REVISION,'input'=>wp_json_encode($input),'instructions'=>$tone_instruction.' '.$base_instructions,'output_schema'=>Structured_Output::EDITORIAL_REVISION_V1,'metadata'=>array('source'=>'editorial_humanizer','source_library_item_id'=>$library_item->get_id(),'tone'=>$data['tone'],'selected_tone'=>$data['tone'],'selected_tone_label'=>$tone_label)); }
	public function build_editorial_revision( AI_Response $response, array $data, $library_item ): Editorial_Revision { $r=$response->to_array(); $out=$response->get_output_json(); if ( empty($out) && '' !== $response->get_output_text() ) { $out=array('revised_content'=>$response->get_output_text()); } return Editorial_Revision::from_ai_response_data($out,array('source_library_item_id'=>$library_item->get_id(),'source_title'=>$library_item->get_title(),'original_summary'=>$library_item->get_summary(),'tone'=>$data['tone'],'default_status'=>Library_Status::NEEDS_REVIEW,'provider'=>$r['provider']??'','model'=>$r['model']??'','request_id'=>$r['request_id']??'')); }
	public function build_library_data( Editorial_Revision $revision, array $data ): array { $title=$revision->get_revised_title()?:__( 'Editorial revision candidate', 'ob-engine' ); return array('title'=>'Editorial Revision: '.$title,'type'=>Library_Type::EDITORIAL_REVISION,'status'=>Library_Status::NEEDS_REVIEW,'source_label'=>$revision->to_array()['source_title']?:__( 'Editorial Humanizer', 'ob-engine' ),'summary'=>$revision->summary(),'content'=>$this->readable_revision_content($revision),'payload_redacted'=>$this->revision_payload_redacted($revision),'created_context'=>'editorial_humanizer'); }
	public function revision_payload_redacted( Editorial_Revision $revision ): string { return wp_json_encode($revision->to_array()); }
	public function readable_revision_content( Editorial_Revision $revision ): string { $out='<h2>'.esc_html($revision->get_revised_title()).'</h2>' . wpautop($revision->get_revised_content()); if ( '' !== $revision->get_revised_excerpt() ) { $out .= '<h3>'.esc_html__( 'Excerpt', 'ob-engine' ).'</h3>'.wpautop(esc_html($revision->get_revised_excerpt())); } return $out; }
}
