<?php
/** Dry-run write safety service. @package OBEngine\Safety */
namespace OBEngine\Safety;
use OBEngine\Activity\Activity_Action;
use OBEngine\Activity\Activity_Logger;
use OBEngine\Activity\Activity_Object_Type;
use OBEngine\Approval\Approval_Repository;
use OBEngine\Approval\Approval_Status;
use OBEngine\Library\Library_Item;
use OBEngine\Library\Library_Repository;
use OBEngine\Library\Library_Status;
use OBEngine\Library\Library_Type;
use WP_Error;
defined( 'ABSPATH' ) || exit;
final class Dry_Run_Service {
	private $library_repository; private $approval_repository; private $dry_run_repository; private $logger;
	public function __construct( Library_Repository $library_repository = null, Approval_Repository $approval_repository = null, Dry_Run_Repository $dry_run_repository = null, Activity_Logger $logger = null ) { $this->library_repository = $library_repository ?: new Library_Repository(); $this->approval_repository = $approval_repository ?: new Approval_Repository( $this->library_repository ); $this->dry_run_repository = $dry_run_repository ?: new Dry_Run_Repository(); $this->logger = $logger ?: new Activity_Logger(); }
	public function run_for_library_item( int $library_item_id, array $target_data = array() ) { $item = $this->library_repository->get( $library_item_id ); if ( ! $item ) { return new WP_Error( 'obe_dry_run_missing_item', __( 'Library item not found.', 'ob-engine' ) ); } $eligibility = $this->can_run_for_item( $item ); $target = $this->build_target( $item, $target_data ); $target_safety = $target->validate(); $safety = $eligibility->is_failed() ? $eligibility : $target_safety; $result = $this->build_result( $item, $target, $safety ); $saved = $this->dry_run_repository->save( $item->get_id(), $result ); if ( is_wp_error( $saved ) ) { return $saved; } $this->log_result( $item, $result, $safety ); return $result; }
	public function can_run_for_item( Library_Item $item ): Safety_Result { if ( $item->get_id() <= 0 || Library_Repository::POST_TYPE !== get_post_type( $item->get_id() ) || 'private' !== get_post_status( $item->get_id() ) ) { return Safety_Result::failed( __( 'Write dry-run failed.', 'ob-engine' ), array( __( 'Only private OBE Library items can be dry-run checked.', 'ob-engine' ) ) ); } if ( Library_Status::APPROVED !== $item->get_status() ) { return Safety_Result::failed( __( 'Write dry-run failed.', 'ob-engine' ), array( __( 'Library item status must be approved before write dry-run can pass.', 'ob-engine' ) ), array( 'library_status' => $item->get_status() ) ); } if ( ! Library_Type::is_writeable( $item->get_type() ) ) { return Safety_Result::failed( __( 'Write dry-run failed.', 'ob-engine' ), array( __( 'Library item type is not writeable.', 'ob-engine' ) ), array( 'library_item_type' => $item->get_type() ) ); } if ( in_array( $item->get_status(), array( Library_Status::ARCHIVED, Library_Status::WRITTEN, Library_Status::FAILED, Library_Status::REJECTED ), true ) ) { return Safety_Result::failed( __( 'Write dry-run failed.', 'ob-engine' ), array( __( 'Dry-run is unavailable for archived, written, failed, or rejected Library items.', 'ob-engine' ) ) ); } $approval = $this->approval_repository->get( $item->get_id() ); if ( Approval_Status::APPROVED !== $approval->get_status() ) { return Safety_Result::failed( __( 'Write dry-run failed.', 'ob-engine' ), array( __( 'Library item must be approved before write dry-run can pass.', 'ob-engine' ) ), array( 'approval_status' => $approval->get_status() ) ); } return Safety_Result::passed( __( 'Library item is approved for write dry-run.', 'ob-engine' ), array( 'approval_status' => Approval_Status::APPROVED ) ); }
	public function build_target( Library_Item $item, array $target_data = array() ): Write_Target { $overrides = array(); if ( isset( $target_data['post_type'] ) ) { $overrides['post_type'] = sanitize_key( (string) $target_data['post_type'] ); } if ( isset( $target_data['post_status'] ) ) { $overrides['post_status'] = sanitize_key( (string) $target_data['post_status'] ); } return Write_Target::from_library_item( $item, $overrides ); }
	public function build_result( Library_Item $item, Write_Target $target, Safety_Result $safety_result ): Dry_Run_Result { $now = current_time( 'mysql' ); $summary = $safety_result->is_passed() ? __( 'Write dry-run passed. No WordPress content was created or changed.', 'ob-engine' ) : __( 'Write dry-run failed. No WordPress content was created or changed.', 'ob-engine' ); return new Dry_Run_Result( array( 'library_item_id' => $item->get_id(), 'status' => $safety_result->get_status(), 'summary' => $summary, 'target' => array( 'post_type' => $target->get_post_type(), 'post_status' => $target->get_post_status() ), 'safety_result' => $safety_result->to_array(), 'result_redacted' => array( 'status' => $safety_result->get_status(), 'summary' => $summary, 'target_post_type' => $target->get_post_type(), 'target_post_status' => $target->get_post_status(), 'blockers_count' => count( $safety_result->get_blockers() ), 'warnings_count' => count( $safety_result->get_warnings() ) ), 'actor_id' => get_current_user_id(), 'created_at' => $now, 'updated_at' => $now ) ); }
	private function log_result( Library_Item $item, Dry_Run_Result $result, Safety_Result $safety ): void { $target = $result->get_target(); $context = array( 'library_item_id' => $item->get_id(), 'library_item_title' => $item->get_title(), 'library_item_type' => $item->get_type(), 'library_status' => $item->get_status(), 'approval_status' => $this->approval_repository->get( $item->get_id() )->get_status(), 'dry_run_status' => $result->get_status(), 'target_post_type' => isset( $target['post_type'] ) ? $target['post_type'] : '', 'target_post_status' => isset( $target['post_status'] ) ? $target['post_status'] : '', 'blockers_count' => count( $safety->get_blockers() ), 'warnings_count' => count( $safety->get_warnings() ) ); $data = array( 'object_type' => Activity_Object_Type::LIBRARY_ITEM, 'object_id' => $item->get_id(), 'object_label' => $item->get_title(), 'message' => $safety->is_passed() ? __( 'Write dry-run passed.', 'ob-engine' ) : __( 'Write dry-run failed.', 'ob-engine' ), 'context' => $context ); if ( $safety->is_passed() ) { $this->logger->success( Activity_Action::WORDPRESS_WRITE_PLANNED, $data ); } else { $this->logger->failed( Activity_Action::SAFETY_CHECK_FAILED, $data ); } }
}
